### ISSUE TITLE
Specify Inter VRF transit Subnet for T0 gateway

### ISSUE THREAD

**Issue by nickliuibm** [vmware/terraform-provider-nsxt#1002]
### Is your feature request related to a problem? Please describe.

We expect to use NSX provider to create T0 gateway by specifying 
- Internal Transit Subnet
- T0-T1 transit Subnet
- Inter VRF Transit Subent

We find the arguments [internal_transit_subnets](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_tier0_gateway#internal_transit_subnets) and [transit_subnets](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_tier0_gateway#transit_subnets) in resource [nsxt_policy_tier0_gateway](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_tier0_gateway) for the first two. 
But for the last one `Inter VRF Transit Subent`, we don't see an argument for it. 
<img width="922" alt="image" src="https://github.com/vmware/terraform-provider-nsxt/assets/39811332/ed836f05-191a-486b-9a1a-272d88f28509">

Can you let use know if NSX provider support specifying  `Inter VRF transit Subnet`

### Describe the solution you'd like

An available argument in resource `nsxt_policy_tier0_gateway` to support  specifying  `Inter VRF transit Subnet`

**Comment by nickliuibm** [comment]
Hell, Any update? Thanks!

**Comment by salv-orlando** [comment]
Hello @nickliuibm  - sorry for our delay.
`vrf_transit_subnets` is an attribute which was added in NSX 4.1.0 and not yet covered by the provider.

We'll take care of ensuring the Tier-0 resource is updated to keep up with the latest NSX release.

**Comment by salv-orlando** [comment]
Hello @nickliuibm  - I believe you are referring to tunnel setting which has been added to localeservice:
`/infra/tier-0s/<tier-0-id>/locale-services/<locale-svc-id>/tunnels/<tunnel-id>`

**Comment by salv-orlando** [comment]
Hello @nickliuibm  - If I understand correctly your ask is to support the new feature for creating N/B GRE tunnels terminated at the T0. Created Issue #1027 for this.
We will scope the work and target it to one of the upcoming releases.
