### ISSUE TITLE
data source nsxt_policy_ip_pool not retrieving the correct id

### ISSUE THREAD

**Issue by dc-tec** [vmware/terraform-provider-nsxt#1006]
### Describe the bug

When using the nsxt_ip_pool data source and retrieving the id. The correct id is not being returned.

For example, we are trying to deploy a nsxt_transport_node and in the ip_assignement block we want to use the static_ip_pool argument. This argument expects an id. 

```terraform
data "nsxt_policy_ip_pool" "overlay_ip_pool" {
  display_name = local.nsx_overlay_ip_pool
}
...
resource "nsxt_transport_node" "edge_transport_node_zone1" {
  for_each = var.vcd_tenant

  display_name = "Edge-${each.value.org_name}-01"
  description  = "Terraform-deployed edge node"

  standard_host_switch {
    host_switch_profile = [data.nsxt_uplink_host_switch_profile.hsw_profile.id]
    host_switch_type    = "NVDS"
    host_switch_mode    = "STANDARD"

    transport_zone_endpoint {
      transport_zone = data.nsxt_policy_transport_zone.overlay_transport_zone.id
    }

    ip_assignment {
      assigned_by_dhcp = false
      static_ip_pool   = data.nsxt_policy_ip_pool.overlay_ip_pool.id
    }
...
```

However the nsxt_policy_ip_pool returns the "wrong" id. In our case it returns "Test-Pool" as the ID. But this doesn't work. When we check the API itself we are getting the following output:

```
{
    "primary": {
        "unique_id": "c67dcb6b-be03-4c1a-a38e-25d6a7cfa4a8",
        "_last_modified_user": "admin",
        "_revision": 0,
        "check_overlap_with_existing_pools": false,
        "owner_id": "d9c2a6b5-5f8b-4e73-9cef-9974440d49a7",
        "_system_owned": false,
        "resource_type": "IpAddressPool",
        "_meta": {
            "identifier": "/infra/ip-pools/Test-Pool",
            "is_global_object": false
        },
        "_protection": "NOT_PROTECTED",
        "realization_id": "c67dcb6b-be03-4c1a-a38e-25d6a7cfa4a8",
        "_last_modified_time": 1697792380259,
        "sync_realization": false,
        "overridden": false,
        "display_name": "Test-Pool",
        "remote_path": "",
        "_create_user": "admin",
        "_create_time": 1697792380259,
        "path": "/infra/ip-pools/Test-Pool",
        "marked_for_delete": false,
        "parent_path": "/infra",
        "id": "Test-Pool",
...
```
In the above output we see that there is also a unique_id field available. Now when we try to use this value in our code for the static_ip_pool argument, we notice that the resource accepts this value.

This was the exact error we where getting:

```
│ [Fabric] DHCP mode is not supported for Edge VTEP IP assignment in HostSwitch nsxDefaultHostSwitch, please provide IP Pool for allocating static ip address. (code 15500) 
│ 
│   with module.vcd_tenant.nsxt_transport_node.edge_transport_node_zone1["dc_tech_tenant"],
│   on ../../_modules/vcd_tenant/nsx_edge_node.tf line 43, in resource "nsxt_transport_node" "edge_transport_node_zone1":
│   43: resource "nsxt_transport_node" "edge_transport_node_zone1" {
│ 
╵
╷
│ Error:  Failed to create TransportNode Edge-DCT-02: Found errors in the request. Please refer to the related errors for details. (code 15000)
│ Related errors:
│ [Fabric] DHCP mode is not supported for Edge VTEP IP assignment in HostSwitch nsxDefaultHostSwitch, please provide IP Pool for allocating static ip address. (code 15500) 
│ 
│   with module.vcd_tenant.nsxt_transport_node.edge_transport_node_zone2["dc_tech_tenant"],
│   on ../../_modules/vcd_tenant/nsx_edge_node.tf line 100, in resource "nsxt_transport_node" "edge_transport_node_zone2":
│  100: resource "nsxt_transport_node" "edge_transport_node_zone2" {
```

### Reproduction steps

1. Create a data nsxt_policy_ip_pool block and retrieve the id from a ip pool you want to use
2. Create a resource nsxt_transport_node block and use the id from the ip pool as the value in your ip_assignment block, use the static_ip_pool argument.
3. Deploy the resource
...

### Expected behavior

Expected the nsxt_policy_ip_pool data source to retrieve the correct Id (or that the nsxt_transport_zone resource correctly translates the static_ip_pool display name to the unique Id)

**Comment by annakhm** [comment]
Hi @dc-tec, thank you for reporting this. The source of confusion here is that NSX exposes two sets of API - the legacy API (deprecated) and Policy API. The provider offers resources and data sources for both sets. Unfortunately, for the same objects, ids are not the same in policy API and old API. 
Since transport node is not yet available via Policy API, it was implemented via old API and expects its dependencies to be derived from old APIs as well. In case of ip pool, `data "nsxt_ip_pool"` would fetch the correct id for you.
However to make consumption easier, we will also add `realized_id` attribute to the policy data source.

**Comment by salv-orlando** [comment]
This issue should be addressed by https://github.com/vmware/terraform-provider-nsxt/pull/1008

**Comment by annakhm** [comment]
`realized_id` was added to the data source and resource
