### ISSUE TITLE
Is there a way to import an existing DFW policy set into terraform ? 

### ISSUE THREAD

**Issue by chanakanissanka** [vmware/terraform-provider-nsxt#1044]
### Describe the bug

Hi there, I guess what I want to get confirmation of here is the possibility of importing or referring existing DFW policy sets into Terraform. These DFW policy sets were created as part of migrations via RestNSX. So outside to the terraform. 

we can see that using the resource below, we can actually query the default policy, not the other policy sets

data "nsxt_policy_security_policy" "predefined" {
  is_default = true
  category   = "Application"

}

Which will give output ==> "/infra/domains/default/security-policies/default-layer3-section"

Is there a similar resource type we are missing to query other policy sets that are not defaulted?

### Reproduction steps

when referring to non-default

 data "nsxt_policy_security_policy" "predefined" {
  is_default = false
  display_name = "XXXX"
  category   = "Application"
  #domain = "/infra/domains/default/security-policies/IDMZ_IN"
}

nsxt_policy_security_policy.policy1: Refreshing state... [id=bb47cc49-efc5-40ef-9dcc-c06a479018e4]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Security Policy with name 'XXXX' and category 'Application' was not found
│ 
│   with data.nsxt_policy_security_policy.predefined,
│   on main.tf line 575, in data "nsxt_policy_security_policy" "predefined":
│ data "nsxt_policy_security_policy" "predefined" {

### Expected behavior

when trying bellow data query it should be able to read the policy name of "XXXX" successfully without error
 data "nsxt_policy_security_policy" "predefined" {
  is_default = false
  display_name = "XXXX"
  category   = "Application"
  #domain = "/infra/domains/default/security-policies/IDMZ_IN"
}

### Additional context

Our end goal here is to be able to perform CRUD operations into these pre-existing DFW policy set

**Comment by 2ez4szliu** [comment]
Hi @chanakanissanka , 
I did not hit this issue when using a data source for security policy that I created on NSX UI.
can you run the NSX GET API on this security policy you are trying to import to make sure the display name and category is correct?
