### ISSUE TITLE
Interoperability with NSX-T v4.1

### ISSUE THREAD

**Issue by liftconfig** [vmware/terraform-provider-nsxt#1047]
### Is your feature request related to a problem? Please describe.

README.md interoperability section only specifies that up to NSX-T 4.0 is supported however, some of the resource documentation specifies v4.1 is required. Is NSX-T v4.1+ supported? Is it possible to create an interoperability matrix outlining the terraform to NSX-T version compatibility?

### Describe the solution you'd like

Updated interoperability section.

**Comment by salv-orlando** [comment]
@liftconfig I will update the README, that's our bad!

The latest Github release of the NSX Terraform providers supports NSX 4.1.2, 4.1.1 and 4.1.0.

**Comment by liftconfig** [comment]
> @liftconfig I will update the README, that's our bad!
> 
> The latest Github release of the NSX Terraform providers supports NSX 4.1.2, 4.1.1 and 4.1.0.

Awesome, thanks for the quick reply and for confirming.
