### ISSUE TITLE
ICMP Service errors and configuration issues

### ISSUE THREAD

**Issue by dcoghlan** [vmware/terraform-provider-nsxt#105]
When trying to create various ICMP services where no icmp_code is provided, the terraform provider is automatically submitting an icmp_code of 0 when creating the service. The end result is a service created that is not the one which was intended to be created.

Here are some examples:

--------------------------------------------------------------------------------
- Intended configuration = Destination unreachable
- Realised configuration = Destination network unreachable
```
resource "nsxt_icmp_type_ns_service" "B012" {
  display_name = "ICMP - Destination unreachable"
  protocol     = "ICMPv4"
  icmp_type    = "3"
}
```
--------------------------------------------------------------------------------
- Intended configuration = Parameter Problem: Bad IP header
- Realised configuration = pointer indicates the error
```
resource "nsxt_icmp_type_ns_service" "B029" {
  display_name = "ICMP - Parameter Problem: Bad IP header"
  protocol     = "ICMPv4"
  icmp_type    = "12"
}
```
---------------------------------------------------------------------------------
- Intended configuration = Redirect Message
- Realised configuration = Redirect Datagram for the Network
```
resource "nsxt_icmp_type_ns_service" "B036" {
  display_name = "ICMP - Redirect Message"
  protocol     = "ICMPv4"
  icmp_type    = "5"
}
```
--------------------------------------------------------------------------------
- Intended configuration = Time Exceeded
- Realised configuration = TTL expired in transit
```
resource "nsxt_icmp_type_ns_service" "B042" {
  display_name = "ICMP - Time Exceeded"
  protocol     = "ICMPv4"
  icmp_type    = "11"
}
```
--------------------------------------------------------------------------------
- When trying to create a service which does not contain a icmp_type or icmp_code, an error is returned as the Terraform provider is submitting a icmp_code of 0 in the backend, when both the icmp_type and icmp_code should be omitted.
```
resource "nsxt_icmp_type_ns_service" "B001" {
  display_name = "ICMP - All"
  protocol     = "ICMPv4"
}
```
**_Error message received_**
``` 
* nsxt_icmp_type_ns_service.B001: Error during NsService create: Status: 400 , Body: {
   "httpStatus" : "BAD_REQUEST",
   "error_code" : 25323,
   "module_name" : "grouping-objects service",
   "error_message" : "Invalid ICMP type, code combination. Type is mandatory, if code is specified."
 } 
```
--------------------------------------------------------------------------------
When trying to create a service for echo-reply, which requires both icmp_type and icmp_code to be set to 0, an error is received.
```
resource "nsxt_icmp_type_ns_service" "B013" {
  display_name = "ICMP - Echo reply"
  protocol     = "ICMPv4"
  icmp_type    = "0"
  icmp_code    = "0"
}
```
**_Error_ message received_**
```
* nsxt_icmp_type_ns_service.B013: Error during NsService create: Status: 400 , Body: {
  "httpStatus" : "BAD_REQUEST",
  "error_code" : 25323,
  "module_name" : "grouping-objects service",
  "error_message" : "Invalid ICMP type, code combination. Type is mandatory, if code is specified."
}
```

**Comment by annakhm** [comment]
@dcoghlan thanks for reporting this!
Fixing with https://github.com/terraform-providers/terraform-provider-nsxt/pull/106
