### ISSUE TITLE
Inter VRF Routing

### ISSUE THREAD

**Issue by scholdan** [vmware/terraform-provider-nsxt#1051]
### Is your feature request related to a problem? Please describe.

I can´t seem to find the option to create Inter VRF Routing?
![image](https://github.com/vmware/terraform-provider-nsxt/assets/23090427/458e3d48-2ee6-4f74-8781-0982c1738fb6)

### Describe the solution you'd like

I will like the option to create it.

**Comment by salv-orlando** [comment]
@2ez4szliu can you please take care of adding this capability to fill this gap in provider's API coverage?
