### ISSUE TITLE
Allow IDS/IPS policies to leverage the 'applied to' field

### ISSUE THREAD

**Issue by SimonRiddle-123** [vmware/terraform-provider-nsxt#1060]
### Is your feature request related to a problem? Please describe.

The 'nsxt_policy_intrusion_service_policy' resource does not allow you to specify an 'applied to', therefore all policies created are applied to the dFW, across all hosts. This is highly inefficient, especially from an IDS/IPS perspective.

Similar functionality is in place for the distributed firewall.

### Describe the solution you'd like

Ability to specify a list of groups that the IDS policy can be applied to.

**Comment by annakhm** [comment]
Hello @SimonRiddle-123, `applied to` attribute is implemented via `scope` attribute of the rule. The attribute is supported and usable, but I notice it is indeed missing from documentation. I will fix the docs. Thanks for reporting this!
