### ISSUE TITLE
VPN Support

### ISSUE THREAD

**Issue by longname123** [vmware/terraform-provider-nsxt#109]
Will there be support for L2 VPN, IPsec VPN and SSL VPN in the future?

Thanks.

**Comment by avoltmer** [comment]
Converting this to an Enhancement as these features do not currently exist in the provider. Note the NSX-T platform only supports L2VPN and IPsec VPN as of the day this note is written.

**Comment by avoltmer** [comment]
@longname123 who are you in real life?

**Comment by longname123** [comment]
Thanks for your reply, I come from China.

**Comment by tvigneron** [comment]
Hello @longname123, if you are a NSX-T customer interested in the feature do not hesitate to give us a name, it always helps prioritize

**Comment by laurentmas** [comment]
Hi, i'm interested for this feature speciallyto create VPN on VMC on AWS platform.

**Comment by etiennejournet** [comment]
Hi, any ETA on this ? Thanks

**Comment by tvigneron** [comment]
Hello Etienne,
This is in our backlog but has not been prioritized so far. Please reach me on tvigneron@vmware.com if you want to detail your use-case.

**Comment by dragoshaidet2** [comment]
+1 on this enhancement

**Comment by slauger** [comment]
Are there any plans to implement the VPN support in the near future?

**Comment by svlady** [comment]
+1 would like to upvote this feature. Having an ability to provision IPSec/L2VPN would be a great help.

**Comment by chrismentjox** [comment]
+1. There is no support for IPsec in either ansible or terraform

**Comment by benzander** [comment]
I'm waiting for IPsec Support of the NSX-T TF Provider as well. There is a Pull request that seems to add support for IPsec / VPN: https://github.com/vmware/terraform-provider-nsxt/pull/724

**Comment by pasikarkkainen** [comment]
https://github.com/vmware/terraform-provider-nsxt/pull/773 added some VPN features.

**Comment by annakhm** [comment]
Closing this as VPN support is now released
