### ISSUE TITLE
Multi-TEP High Availability

### ISSUE THREAD

**Issue by msyretis** [vmware/terraform-provider-nsxt#1097]
### Is your feature request related to a problem? Please describe.

Multi-TEP High Availability
https://docs.vmware.com/en/VMware-NSX/4.1/administration/GUID-72C2F2B2-7DC6-49A2-AD74-2FBAC93E3FAC.html

I would like if possible to be able to create the profile and reference it in the transport node profile.
this saves me a manual step of doing this by hand/ansible.

### Describe the solution you'd like

a data and resource block for the TEP HA host switch profile

```
{
"enabled": "true",
"failover_timeout":"5",
"auto_recovery" : "true",
"auto_recovery_initial_wait" : "300",
"auto_recovery_max_backoff" : "86400",
"resource_type": "PolicyVtepHAHostSwitchProfile",
"display_name": "VtepHAProfile1"
}
```

and then be able to reference to it in the transport node profile

```
        "host_switches": [
            {
                "host_switch_name": "vtepha_vds",
                "host_switch_id": "50 22 ee c4 f6 40 79 8b-0e a4 2b da 6a 4c 36 b3",
                "host_switch_type": "VDS",
                "host_switch_mode": "ENS_INTERRUPT",
                "host_switch_profile_ids": [
                    {
                        "key": "UplinkHostSwitchProfile",
                        "value": "/infra/host-switch-profiles/b32e6ce6-f1ba-4e31-a2c4-33d550505cdd"
                    },
                    {
                        "key": "VtepHAHostSwitchProfile",
                        "value": "/infra/host-switch-profiles/vtephaprofile1"
                    }
                ],
```

### Describe alternatives you've considered

Ansible or manually get/put with postman

**Comment by salv-orlando** [comment]
I think we can surely consider this. @ksamoray do you think it might be feasible?

Targeting this to milestone 3.6.0 as 3.5.0 is quite close.
