### ISSUE TITLE
Error: Failed to retrieve NSX version (com.vmware.vapi.std.errors.service_unavailable).

### ISSUE THREAD

**Issue by DominicMagnus** [vmware/terraform-provider-nsxt#1099]
### Describe the bug

Have the problem on NSX 4.1.2

##########################
error:

terraform plan

Planning failed. Terraform encountered an error while generating this plan.

│ Error: Failed to retrieve NSX version (com.vmware.vapi.std.errors.service_unavailable). Please check connectivity and authentication settings of the provider
│
│ with provider["registry.terraform.io/vmware/nsxt"],
│ on nsx.tf line 10, in provider "nsxt":
│ 10: provider "nsxt" {

######################
Script 

terraform {
 required_version = ">= 1.1.4"
 required_providers {
    nsxt = {
      source = "vmware/nsxt"
      version = "3.4.0"
    }
  }
}

provider "nsxt" {
  host                 = "*****.local"
  username             = "*****"
  password             = "*****"
  allow_unverified_ssl = true
 #remote_auth = false
  max_retries           = 10
  retry_min_delay       = 500
  retry_max_delay       = 3000
  retry_on_status_codes = [429]
}

data "nsxt_policy_bfd_profile" "test" {
  display_name = "profile1"
}

 

######################
server info:

curl -ku user https://*************/api/v1/node

Enter host password for user 'terraform':
{
  "_schema": "NodeProperties",
  "_self": {
    "href": "/node",
    "rel": "self"
  },
  "cli_coredump_config": {
    "global_file_limit": 2,
    "global_frequency_threshold": 600,
    "process_config": []
  },
  "cli_history_size": 100,
  "cli_output_central": false,
  "cli_output_datetime": true,
  "cli_timeout": 600,
  "export_type": "UNRESTRICTED",
  "hostname": "*******************",
  "kernel_version": "5.15.123-nn2-server",
  "motd": "",
  "node_type": "NSX Manager",
  "node_uuid": "*******************************",
  "node_version": "4.1.2.0.0.22589046",
  "product_version": "4.1.2.0.0.22589037",
  "system_datetime": "2024-02-06T10:13:05Z",
  "system_time": 1707214385371,
  "timezone": "Etc/UTC"
}

### Reproduction steps

1.terraform plan
2.error
3.
...

### Expected behavior

retrieve NSX version

**Comment by ksamoray** [comment]
Hi @DominicMagnus,
Can you set the environment variables:
```
export TF_LOG=DEBUG
export TF_LOG_PROVIDER=DEBUG
export TF_LOG_PROVIDER_NSX_HTTP=1
```
and retry planning? And then paste here the output?

**Comment by DominicMagnus** [comment]
After removing the confidential information, such a request remained in a loop:

provider.terraform-provider-nsxt_v3.4.0: 2024/02/06 10:56:58 Error completing client request 'Get "https://nsx-manager.local/api/v1/node/version": dial tcp: lookup nsx-manager.local on 127.0.0.53:53: server misbehaving': timestamp=2024-02-06T10:56:58.651Z

**Comment by ksamoray** [comment]
@DominicMagnus,
Can you replace hostname specification with NSX's IP address, for the sake of troubleshooting?

**Comment by DominicMagnus** [comment]
Yes, the issue was with DNS. After fixing /etc/resolv.conf, the server started responding. Thanks for the help with the logs!
