### ISSUE TITLE
Problem to import segment created by HCX in NSX in VMC

### ISSUE THREAD

**Issue by gmoulard** [vmware/terraform-provider-nsxt#1110]
### Describe the bug

hi, 

When I create a segment in my VMC's NSX, I can import it into my tfstate.
Unfortunly when the segment is created by HCX, in my VMC's NSX, I can not import it on my tfstate. 

The requeted API by provider « GET /policy/api/v1/infra/segments » don't find the segment !!! 
And yet, the segement is visible in NSX consol and in NSX API "POST /policy/api/v1/search/aggregate?page_size=50&cursor=0&sort_by=display_name&sort_ascending=true" 

In // I have an SR opened with vmware support on the same problem SR 24491732101

Best regard, 
Guillaume 

### Reproduction steps

1. terraform import nsxt_policy_segment.segments[\"rec-test\"] rec-test

### Expected behavior

import segment rec-test in nsxt_policy_segment.segments[\"rec-test\"

**Comment by salv-orlando** [comment]
Hello,

The search aggregate API query you reported does not specify the resource_type.
I might be wrong but I think the segment created by HCX are tier-1 segments.

Which resource or data source did you use?
Did you try using `nsxt_policy_fixed_segment` as well?

@annakhm moving this into your queue.

**Comment by gmoulard** [comment]
Hello,

I use nsxt_policy_segment  in my case. I don't test nsxt_policy_fixed_segment.

My Code; 
`resource "nsxt_policy_segment" "segments" {
  lifecycle {
    ignore_changes = [security_profile]
  }

  for_each            = local.segments
  display_name        = each.key
  description         = each.value.description
  connectivity_path   = "/infra/tier-1s/cgw"
  transport_zone_path = data.nsxt_policy_transport_zone.transport_zone.path

  tag {
    scope = each.value.env
    tag   = "env"
  }
  tag {
    scope = each.value.app
    tag   = "app"
  }
  subnet {
    cidr = each.value.subnet
  }
  advanced_config {
    connectivity = "OFF"
  }
}`

**Comment by gmoulard** [comment]
Indeed my import works with an nsxt_policy_fixed_segment. what are the differences between nsxt_policy_fixed_segment and nsxt_policy_segment?

**Comment by annakhm** [comment]
Hi @gmoulard, segment and fixed segment are different API endpoints in NSX, fixed segment is always attached to a gateway, while regular segment can be detached. Other than that, those segments are very similar.
