### ISSUE TITLE
Role binding update for local users need identity_source_type

### ISSUE THREAD

**Issue by jduepmeier** [vmware/terraform-provider-nsxt#1123]
### Describe the bug

When updating a role binding for a local user the update fails with
```
Failed to create RoleBinding 34fa87c3-31b6-4457-94dd-ec652b680cef: Field level validation errors: {value  of property identity_source_type is not one of the allowed values [VIDM, LDAP, OIDC, CSP]} (code 255)
```

With the identity_source_type set to VIDM the update does work but now every apply tries to update the resource.

### Reproduction steps

1. Create a local user
```terraform
resource "nsxt_node_user" "test" {
    active = true
    full_name = "Test"
    password = "Secure!Password123"
  username = "test"
}
```
2. Add role binding
```terraform
resource "nsxt_policy_user_management_role_binding" "test" {
  display_name         = "test"
  name                 = "test"
  type                 = "local_user"

  roles_for_path {
    path = "/"
    role {
      role = "auditor"
    }
  }
}
```
3. Import existing resource as describe in the terraform provider documentation
4. Change something and apply

### Expected behavior

Successful apply.

**Comment by wsquan171** [comment]
Hi,

I couldn't reproduce the issue on my end. Could you confirm that the correct role binding ID is used? It's most likely the ID of a different non-local user role binding is used for the import.

Could you check `terraform show` after import and check if `identity_source_type` is in the imported role binding? Normally no `identity_source_type` is expected for local users.

**Comment by jduepmeier** [comment]
Hello @wsquan171 ,

sorry for the long delay. Maybe the id was wrong. It does not happen anymore.

I think it would be better to include the role binding inside the `nsxt_node_use`.
This would fix the manual import of the role binding:
```terraform
resource "nsxt_node_user" "test-user" {
  active = true
  full_name = "Test User"
  ...

  roles_for_path {
    path = "/"
    roles = [
       "enterprise_admin"
    ]
  }
}
```

The resource would than create the user, gets the role binding id and then updates the role binding.
