### ISSUE TITLE
Add Support for Metadata Proxy Profile

### ISSUE THREAD

**Issue by benzander** [vmware/terraform-provider-nsxt#1142]
### Is your feature request related to a problem? Please describe.

We would like to use the nsx-t metadata proxy feature

### Describe the solution you'd like

Can you please add a resource for Metadata Proxy Profile:
![image](https://github.com/vmware/terraform-provider-nsxt/assets/99820917/d8d929f6-1879-4eb4-a003-eef3153eed31)

And add and attribute to the nsxt_policy_segment to link the metadata proxy profile

![image](https://github.com/vmware/terraform-provider-nsxt/assets/99820917/3ab9ced0-86a7-4de1-8b5d-f8b30bfb3544)

**Comment by ksamoray** [comment]
@benzander how do you plan to utilize this resource? As AFAIK metadata proxy is only usable with OpenStack.

**Comment by benzander** [comment]
@ksamoray: Yes I know that this feature was made for Openstack. We are developing our own metadata service in the background which relies on this md proxy feature.
