### ISSUE TITLE
Data Source - Port

### ISSUE THREAD

**Issue by benfairclough** [vmware/terraform-provider-nsxt#117]
Ability to pull port data source from NSX-T using filters

**Comment by yasensim** [comment]
@benfairclough can you explain the use-case please?
Why would you need port data source?

**Comment by David-VTUK** [comment]
One use case I can think of is tagging individual ports, which is a requirement for the K8s NSX-T CNI plugin. Maybe this issue can be a workaround for https://github.com/terraform-providers/terraform-provider-nsxt/issues/248
