### ISSUE TITLE
Custom Context Profiles with custom attributes

### ISSUE THREAD

**Issue by Antonvankan** [vmware/terraform-provider-nsxt#1275]
### Describe the bug

When createing a custom attribute from a string one is unable to add multiple attributes to a single custom context profile

### Reproduction steps

resource "nsxt_policy_context_profile_custom_attribute" "custom_domainname" {
      for_each = var.map_contextprofile_domainname
      key       = "DOMAIN_NAME"
      attribute = each.value
}
resource "nsxt_policy_context_profile" "custom_domainname" {
for_each = var.map_contextprofile_domainname
display_name = each.key
description  = "Terraform provisioned ContextProfile"
 domain_name {
     value       = [each.value]
    }
  depends_on = [nsxt_policy_context_profile_custom_attribute.custom_domainname]
}

╷
│ Error: Missing attribute value
│ 
│   on main.auto.tfvars line 39:
│   38: map_contextprofile_default = {
│   39:   cloudapp = "*.cloudapp.net","*-files.sharepoint.com"
│   40: }
│ 
│ Expected an attribute value, introduced by an equals sign ("=").

### Expected behavior

multiple values added to a context profile

**Comment by annakhm** [comment]
Hi @Antonvankan, from the info you provided it looks like the syntax is incorrect in your `main.auto.tfvars` file. terraform expects a single quoted string after the `=` sign.

**Comment by annakhm** [comment]
Closing this per previous comment. Please reopen if issue is other than incorrect syntax.
