### ISSUE TITLE
 Resource to add licence key to NSX manager

### ISSUE THREAD

**Issue by shearsey** [vmware/terraform-provider-nsxt#1465]
### Is your feature request related to a problem? Please describe.

Full automation of the NSX manager deplyment is not possible because ethere is no resource to licence the manager, this block the ability to configure some further resources that rely on the licence.

### Describe the solution you'd like

A resource to add licences to the NSX manager

### Describe alternatives you've considered

Separate script to add the licence via the API

**Comment by ksamoray** [comment]
@shearsey licenses can be set with the `license_keys` attribute of the [provider](https://registry.terraform.io/providers/vmware/nsxt/latest/docs).
LMK if that works for you.

**Comment by shearsey** [comment]
Easy when you know how, that was what i have searched for in the terrform registry documentation, in future i'll search the git repo as well, thank you
