### ISSUE TITLE
Tier0 Router HA VIP Configuration

### ISSUE THREAD

**Issue by ScriptXaaS** [vmware/terraform-provider-nsxt#172]
Please provide a resource object to configure HA VIP for T0 Router.  On GUI, it could be done via
Advanced Networking & Security > Router > T0 Router Name > Configuration > HA VIP

**Comment by annakhm** [comment]
Hi @ScriptXaaS  - this resource was added with https://github.com/vmware/terraform-provider-nsxt/pull/420. Please note that this resource is still experimental, we expect it to be officially supported with 3.1.0 release.
