### ISSUE TITLE
Error during DhcpProfile create: Status: 400 Bad Request, Body: Bad Request This combination of host and port requires TLS.

### ISSUE THREAD

**Issue by kamalika-majumder** [vmware/terraform-provider-nsxt#198]
I have a NSX Manager and 1 nsx edge services gateway managed through Vcenter.
I have tested the nsx manager api for edge services and its returning me the right values.

Get api/4.0/edges

My module is as below:
===================
provider "nsxt" {
  host                  = var.nsxt_manager
  username              = var.nsxt_username
  password              = var.nsxt_password
  allow_unverified_ssl  = true
  max_retries           = 10
  retry_min_delay       = 500
  retry_max_delay       = 5000
  retry_on_status_codes = [429, 400]
}

#data "nsxt_edge_cluster" "edge_cluster1" {
#  display_name = "edge-1"
#}

resource "nsxt_dhcp_server_profile" "prf" {
  description                 = "dhcp_profile provisioned by Terraform"
  display_name                = "dhcp_profile"
  edge_cluster_id             = "domain-c7"
  edge_cluster_member_indexes = [0]
  tag {
    scope = "env"
    tag   = "admin"
  }
}

resource "nsxt_logical_dhcp_server" "logical_dhcp_server" {
  display_name    = "logical_dhcp_server"
  dhcp_profile_id = "${nsxt_dhcp_server_profile.prf.id}"
  dhcp_server_ip  = "10.70.10.2/24"
  gateway_ip      = "10.70.10.253"
}

resource "nsxt_dhcp_server_ip_pool" "public_ip_pool" {
  display_name           = "ip pool"
  description            = "ip pool"
  logical_dhcp_server_id = "${nsxt_logical_dhcp_server.logical_dhcp_server.id}"
  gateway_ip             = "10.70.10.253"
  lease_time             = 86400
  error_threshold        = 98
  warning_threshold      = 70

  ip_range {
    start = "10.70.10.1"
    end   = "10.70.10.252"
  }

  tag {
    scope = "env"
    tag   = "admin"
  }

}

can you let me know if this provider works on the above setup

**Comment by tvigneron** [comment]
Hello Kamalia.
The fact that you are talking about edge service gateway and using api/4.0/edges makes me think you are using NSX for vSphere.
This terraform Provider is for NSX Transformer which is the next generation of NSX but offers a different API surface and changes in the architecture. 
That is why your file won't work in this setup.
There is examples of community based Terraform provider for NSX vsphere that might get you the result you expect. For example https://github.com/sky-uk/terraform-provider-nsx .
But we are not working on those here.
