### ISSUE TITLE
Configure HA VIP on Policy Tier0 Router

### ISSUE THREAD

**Issue by nvpnathan** [vmware/terraform-provider-nsxt#289]
terraform -v
Terraform v0.12.24
+ provider.nsxt v2.0.0
+ provider.vsphere v1.17.1

resource "nsxt_policy_tier0_gateway" "tier0_gw" {
  description               = "Tier-0 provisioned by Terraform"
  display_name              = var.t0_rtr_01
  failover_mode             = "PREEMPTIVE"
  default_rule_logging      = false
  enable_firewall           = false
  ha_mode                   = "ACTIVE_STANDBY"
  edge_cluster_path         = data.nsxt_policy_edge_cluster.edge_cluster_01.path

  tag {
    scope = "tkg"
    tag   = "tanzu"
  }
}

**Comment by pokepoke81** [comment]
I second the need for this one.

**Comment by annakhm** [comment]
Hi @nvpnathan, @pokepoke81 - this resource was added with https://github.com/vmware/terraform-provider-nsxt/pull/420. Please note that this resource is still experimental, we expect it to be officially supported with 3.1.0 release.
