### ISSUE TITLE
Ability to Apply NSX product license keys

### ISSUE THREAD

**Issue by jmarhee** [vmware/terraform-provider-nsxt#378]
Similar to the [vSphere provider,](https://www.terraform.io/docs/providers/vsphere/r/license.html) I'd like to request a feature to apply an NSX-T license (i.e. for the DCA product) via Terraform as well.

**Comment by displague** [comment]
I believe this is looking for a resource and perhaps a data source that implements this API: <https://www.vmware.com/support/nsxt/doc/nsxt_20_api.html#Sections.Licensing>

It seems https://github.com/vmware/terraform-provider-nsxt/pull/423 is getting the resource in place.

@jmarhee Do you have the need for a data source too?

**Comment by annakhm** [comment]
Hi @jmarhee, @displague - ability to apply NSX licenses was added as part of provider here https://github.com/vmware/terraform-provider-nsxt/pull/423 - does it work for you?

**Comment by jmarhee** [comment]
Thanks #423 appears to accomplish exactly what I'd like
