### ISSUE TITLE
Get paths for route maps on Tier0

### ISSUE THREAD

**Issue by pokepoke81** [vmware/terraform-provider-nsxt#383]
Looking at BGP Neighbor config, is there a way to create or programmatically get the path to a route map? 

[BGP Neighbor Policy](https://www.terraform.io/docs/providers/nsxt/r/policy_bgp_neighbor.html)

I'm looking to set the out filter 

`out_route_filter- (Optional) Path of prefix-list or route map to filter routes for OUT direction.`

I can hard code it in, but how can I set it as a data source?

**Comment by tvigneron** [comment]
Hello,
The data source is not available as of now, it is on the roadmap.

**Comment by pokepoke81** [comment]
What is the format for the paths? I'm currently trying it like this, but it doesn't work. No error and no out route:

out_route_filter    = "/infra/tier-0s/a5cc9929-d9eb-4d7e-affa-bbc2cee771dd/route-maps/Primary_Policy"

That string is the policy path I copy from the NSX UI.

**Comment by annakhm** [comment]
Thanks @pokepoke81, indeed there is a bug in this area. Fixing with https://github.com/terraform-providers/terraform-provider-nsxt/pull/387

**Comment by annakhm** [comment]
Route Map resource was added, thus closing this.
