### ISSUE TITLE
Unable to use various DataSource when more than 50 items exists

### ISSUE THREAD

**Issue by dstoffel** [vmware/terraform-provider-nsxt#412]
Hello,

I have some error with different kind of DataSource when more then 50 items exists in NSX and the entry i'm looking for is after the 50 first items returned.

For example, with a NS Group :

```
data "nsxt_ns_group" "mynsgroup" {
   display_name="mynsgroup"
}
```

The following error is returned:

```
Error: NS group with name 'mynsgroup' was not found amoung 50 groups
```

After a quick check, i noticed the TODO (nsxt/data_source_nsxt_ns_group.go for example)

```
            // TODO use 2nd parameter localVarOptionals for paging
                objList, _, err := nsxClient.GroupingObjectsApi.ListNSGroups(nsxClient.Context, nil)
                if err != nil {
                        return fmt.Errorf("Error while reading NS groups: %v", err)
                }
                // go over the list to find the correct one
                found := false
                for _, objInList := range objList.Results {
                        if objInList.DisplayName == objName {
                                if found {
                                        return fmt.Errorf("Found multiple NS groups with name '%s'", objName)
                                }
                                obj = objInList
                                found = true
                        }
                }
                if !found {
                        return fmt.Errorf("NS group with  name '%s' was not found among %d groups", objName, len(objList.Results))
```

Is the pagination handling is coming soon  or should i try to PR a fix ?

Thanks,
Davy

**Comment by annakhm** [comment]
Hello @dstoffel and thanks for filing this. We intend to fix all these issues using search API once we drop support of NSX 2.5 (where search API is not officially supported). Please feel free to file a PR, and we'll try to accommodate this sooner as well, since we know there is a demand.

**Comment by asarfaty** [comment]
As far as I see in the SDK code, there is a specific limitation to the ns-groups limiting each page to 50.
This will be fixed with this pull request: https://github.com/vmware/terraform-provider-nsxt/pull/440
I didn't see the same issue with other data sources.
