### ISSUE TITLE
Provide support to create ip discovery profiles

### ISSUE THREAD

**Issue by waza-ari** [vmware/terraform-provider-nsxt#414]
Currently, the provider supports discovery providers as data source and also to use them on a segment (although its an undocumented feature, its not shown here: https://www.terraform.io/docs/providers/nsxt/r/policy_segment.html)

We should also provide the ability to create an IP Discovery Policy (same for the other segment policies I guess) to manage the policies in Terraform. As far as I can tell, the SDK already supports that.

**Comment by alagoutte** [comment]
Hello,

I need also Discovery Profiles for segment (on my case policy_mac_discovery_profiles) but it is not available :(
I see there is a policy_qos_profile (very similar) 

i can may be help for add this profiles (but need help !)

**Comment by alagoutte** [comment]
i start to work on add policy_mac_discovery (with #692) after it will be merge, i can look for add also Policy IP Discovery too (it not be too complicated)

**Comment by jmcleese** [comment]
Hello, what is the status on having an policy_ip_discovery resource?

**Comment by alagoutte** [comment]
Thanks @ksamoray !
