### ISSUE TITLE
Add LB rules to nsxt_policy_lb_virtual_server configuration 

### ISSUE THREAD

**Issue by neil-wwt** [vmware/terraform-provider-nsxt#444]
Currently, [nsxt_policy_lb_virtual_server](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_lb_virtual_server) does not support the configuration of LB rules, which the UI does. 

It appears [these rules were supported](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/lb_http_request_rewrite_rule) with the manager API, but from what I can tell the rules in the Policy API are distinct.

Here are some screens of the LB rules in the NSX-T UI. 
![Virtual Server screen with Rules section](https://user-images.githubusercontent.com/22230865/92041317-3ebf5e80-ed35-11ea-9bce-62cafa33ad0b.png)
![One of several screens to add a new rule](https://user-images.githubusercontent.com/22230865/92041321-41ba4f00-ed35-11ea-81ca-501ab795abf2.png)

It would be great if the provider support the creation of these rules in the Policy API. Lots of customers rely on this sort of functionality.

**Comment by MartinRohrbach** [comment]
I would like to bump this as we would like to change our terraform code from manager to policy UI but are unable to provision LB virtual servers with LB rules.

**Comment by m-garrido** [comment]
Same here. I don't understand why this feature is always missing since the creation of this issue.
Offering the ability to deploy a load balancer without rules, it's really limiting.
This issue must be prioritized.

**Comment by annakhm** [comment]
Closing this as rules are now supported (thanks @martinrohrbach!)
