### ISSUE TITLE
LB Rules are removed when nsxt_policy_lb_virtual_server resource is changed 

### ISSUE THREAD

**Issue by neil-wwt** [vmware/terraform-provider-nsxt#445]
_Related to this enhancement request: https://github.com/vmware/terraform-provider-nsxt/issues/444_

LB rules are part of the Virtual Server configuration in NSX-T but not yet supported by the provider, and need to be created manually in the UI.

If the Virtual Server is created by Terraform, then a rule added manually and the resource is updated by terraform, all rules are deleted.

## Steps to reproduce
- Create a new VIP with all defaults (details don't matter). Something like...

```
resource "nsxt_policy_lb_virtual_server" "test" {
  display_name               = "test"
  description                = "Terraform provisioned Virtual Server"
  application_profile_path   = "/infra/lb-app-profiles/default-http-lb-app-profile"
  ip_address                 = "10.10.10.21"
  ports                      = ["443"]
}
```
- From the UI, add a LB rule to that VIP you just created.
![Add LB rule to VIP](https://user-images.githubusercontent.com/22230865/92042268-15073700-ed37-11ea-975f-82ce1af38590.png)

- Change any detail in the Terraform code, like the profile path. 
- `terraform plan` will say 1 to change and show your change.
- `terraform apply`
- Check the UI. The rule is gone.

## Expected/desired behavior
- Ideally be would be able to actually [manage these rules in code](https://github.com/vmware/terraform-provider-nsxt/issues/444) (addressing that issue would render this one moot)
- Or it would be great if Terraform only updated the attributes of the resource it knew about and did not do a full replace 
- Or, if Terraform could warn the user that the resource has changed and that this "change" could actually be destructive outside of what is shown in the plan.
- Or, if the API only allows for a full replace, TF should reflect that as a delete and recreate, not a change.

**Comment by tvigneron** [comment]
That is the expected behaviour of Terraform to be the source of truth of the objects it configures. In this context it is normal that when you apply your Terraform file, it creates the configuration mapped to the intent of the terraform file.

There is a Terraform setting ignore_changes you can get a look at  which might help (https://www.terraform.io/docs/configuration/resources.html).

However

**Comment by tvigneron** [comment]
Generally when your intent is described/managed by a tool, modifying the resulting objects outside of the tool will lead into some disconnects/override etc..

**Comment by annakhm** [comment]
Thank you @neil-wwt, this is addressed with https://github.com/vmware/terraform-provider-nsxt/pull/480
Alternatively, you can manually enable partial patch updates on NSX, if your NSX version supports this API:
`PATCH /policy/api/v1/system-config/nsx-partial-patch-config
{
    "enable_partial_patch": true
}
`
Hope this helps.
