### ISSUE TITLE
New data source that returns multiple VMs

### ISSUE THREAD

**Issue by neil-wwt** [vmware/terraform-provider-nsxt#446]
The current data source for VMs ([nsxt_policy_vm](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/data-sources/policy_vm)) only allows for returning attributes about a single VM.

It would be really useful if there was a data source that returned a list of VMs similar to the [aws_instances](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/instances) data source.

The arguments for this data source would need more capabilities like pattern matching or filters of course.

## Suggested Example
```
data "nsxt_policy_vms" "ubuntu_vms" {
  filter {
    OS = "Ubuntu"
    display_name = "web*"
  }
}
```
This would return all VMs with an Ubuntu OS and a name that starts with `web` (regex patterns would be _really_ great here)

Then from this you could do something like apply a tag to each VM using its instance ID
```
resource "nsxt_policy_vm_tags" "web_servers" {
  for_each = data.nsxt_policy_vms.ubuntu_vms.instance_ids
  instance_id = each.value

  tag {
    tag   = "Web"
  }
}
```

**Comment by annakhm** [comment]
Filtering by state and guest_os was added for `nsxt_policy_vms` in https://github.com/vmware/terraform-provider-nsxt/pull/869
Sorry it took such a long time!
