### ISSUE TITLE
Error with NSXT terraform provider 

### ISSUE THREAD

**Issue by vbuild2bau** [vmware/terraform-provider-nsxt#454]
I found what the issue was with the error, it appears that the provider is not accepting the alias meta-argument as per

https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations

As we has 2 SDDC's, therefore 2 NSX-T appliances I was trying to alias the provider block so that all the networking could be configured in one place, looks like this will need to be broken up per SDDC until we are able to use multiple provider configurations

Just for reference

working
provider "nsxt" {
host = var.host
vmc_token = var.api_token
allow_unverified_ssl = true
enforcement_point = "vmc-enforcementpoint"
}

fails
provider "nsxt" {
host = var.host
vmc_token = var.api_token
allow_unverified_ssl = true
enforcement_point = "vmc-enforcementpoint"
alias = "sddc1"
}

**Comment by annakhm** [comment]
Hello @vbuild2bau, could you please specify what your error is. I don't see any issues with alias in the provider.

**Comment by vbuild2bau** [comment]
The error I was seeing was

------------------------------------------------------------------------

Error: username must be provided

  on <empty> line 0:

  (source code not available)

However, I’ve combined the code after this email and im not getting the error anymore
