### ISSUE TITLE
VRF Lite Configure Access VLAN on VRF Interfaces

### ISSUE THREAD

**Issue by raymonddejong** [vmware/terraform-provider-nsxt#455]
As an NSX Administrator I would like to configure VRF lite. When configuring VRF I configure Interfaces/Uplinks and select the VLAN Trunk Segment to connect to and want to specify an Access VLAN per VRF to connect to the network. I am able to configure the interface and segment it connects to but I need the ability to configure an Access VLAN too. 
![image](https://user-images.githubusercontent.com/41117526/92701476-5491dc80-f350-11ea-9bdd-4445d6c37ddf.png)

**Comment by tvigneron** [comment]
Hello Raymond,
I the Tier-0 interface resource:
https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_tier0_gateway_interface
There is an optional argument for Access VLAN Id:
access_vlan_id- (Optional) Access VLAN ID, relevant only for VRF interfaces. This attribute is supported with NSX 3.0.0 onwards.
Have you tried this ? Does it fail to solve the use-case?

**Comment by raymonddejong** [comment]
Hi, yes I've found it and tried it this morning and it works. 
Totally missed this/overlooked option in the docs.
Thanks for pointing me to it.
