### ISSUE TITLE
Use IP Set for security policy

### ISSUE THREAD

**Issue by keachi** [vmware/terraform-provider-nsxt#464]
# Sumary
I want to deploy a policy security policy with an ip set as source group. It is possible to set this in the web GUI, but I can't deploy it with Terraform.

I deployed an IP Set with Terraform:
![image](https://user-images.githubusercontent.com/1687482/93345433-1a827800-f833-11ea-839e-211f4a43542d.png)
and I can select this IP Set in the web GUI:
![image](https://user-images.githubusercontent.com/1687482/93345798-882ea400-f833-11ea-96b8-3fa4703d81c0.png)

I used the documentation of [policy security policy](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_security_policy) to deploy a security policy with Terraform and I want to add a rule with the IP Set from above.

# Code
```
resource "nsxt_ip_set" "ip_set" {
  display_name = "cme_st0_prd_oob"
  description  = "CME ST0 PRD OOB"
  ip_addresses = [
    "192.0.2.0/24",
  ]
}

resource "nsxt_policy_security_policy" "default" {
  display_name = "cme_st0_prd_oob"
  description  = "CME ST0 PRD OOB"
  category     = "Application"
  scope        = [nsxt_policy_group.xy.path]

  rule {
    display_name       = "first rule"
    destination_groups = [nsxt_ip_set.ip_set.???]
    action             = "ALLOW"
    logged             = true
  }
}
```

# Versions
```
Terraform v0.13.0
+ provider registry.terraform.io/terraform-providers/nsxt v3.0.1
```
VMware NSX-T Version 2.5.1.4.0.16132225

# Question
Is this only a not documented feature, and it's already possible to use IP Sets for source and/or destination groups or isn't it implemented yet?
If it's not documented, can you either document it officially or can you provide me the information how I can deploy/use it? Or if needed, can you implement it?

**Comment by tvigneron** [comment]
Hello Tovias,
Why don't you simply asign the IP address in your Policy group.
IPset is an object from the MP API while in the Policy API everything is a group so it is cleaner to do a group of IPs.
(You can do groups with only IPs if you want to have specific groups).
https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_group

ipaddress_expression - (Optional) An expression block to specify individual IP Addresses, ranges of IP Addresses or subnets for this Group.

**Comment by keachi** [comment]
It did it this way, as at the moment there is no data source for policy groups (it will be in the future, see #439). So I tried to do it with an IP Set. In real those two resources are not in the same project.
