### ISSUE TITLE
Unable to configure Layer2 Bridge Firewall 

### ISSUE THREAD

**Issue by dcoghlan** [vmware/terraform-provider-nsxt#470]
This is more of a feature request.

It appears that the terraform provider is unable to configure the Layer2 Bridge Firewall. 

When will support for the Layer2 Bridge Firewall be available in the NSX-T Terraform Provider?

**Comment by pandom** [comment]
Hey!

When will L2 Bridge firewall rules be supported by the Policy API? Currently we can configure the Bridge via Terraform but we lack any ability to configure L2Bridge Firewall rules with Terraform.

Thanks!
Anthony Burke
(Hi Dale!!)

**Comment by annakhm** [comment]
This feature was added with 3.3.0 release
