### ISSUE TITLE
Documentation example correction for nsxt_policy_segment_realization

### ISSUE THREAD

**Issue by Sonic-Pancake** [vmware/terraform-provider-nsxt#471]
https://registry.terraform.io/providers/vmware/nsxt/latest/docs/data-sources/policy_segment_realization

The data. under realization path should not be there but it should be used vsphere_network name = data.

The example usage should read as per below:

resource "nsxt_policy_segment" "s1" {
  display_name        = "segment1"
  transport_zone_path = data.nsxt_transport_zone.tz1.path
}

data "nsxt_policy_segment_realization" "s1" {
  path = nsxt_policy_segment.s1.path
}

# usage in vsphere provider
data "vsphere_network" "net" {
  name          = **data.**nsxt_policy_segment_realization.s1.network_name
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

**Comment by annakhm** [comment]
Thanks for spotting this, docs corrected with https://github.com/vmware/terraform-provider-nsxt/pull/477
