### ISSUE TITLE
Updating Segment clears Bridge configuration

### ISSUE THREAD

**Issue by mdegrasse** [vmware/terraform-provider-nsxt#483]
When updating a Segment (for example changing name) that has an Edge Bridge association, the association is deleted.

TF 0.13 with NSX-T 3.0.1 provider

**Comment by tvigneron** [comment]
Hello mdegrasse
We do not support the Edge Bridge configuration on the NSX-T Terraform Provider.
As Terraform is not aware of those, when Terraform is applied those are not applied configurations are removed (not in the intent file).
We have in roadmap to cover the Edge bridge.

**Comment by netmemo** [comment]
Hello, I'm also really interested in the support of the Edge Bridge into Terraform. At least managing a segment through Terraform should not break the Edge Bridge association.
