### ISSUE TITLE
Creating nsxt_policy_segment resources against VMware Cloud on AWS NSX-T produces unsupported results

### ISSUE THREAD

**Issue by jdhawks50** [vmware/terraform-provider-nsxt#490]
When using `nsxt_policy_segment` to create NSX-T segments in VMware Cloud on AWS, the resulting segment created is officially unsupported by VMware.

The below code produces a segment in VMC:
```
data "nsxt_policy_transport_zone" "cgw_transport_zone" {
    is_default = true
    transport_type = "OVERLAY_STANDARD"
}

resource "nsxt_policy_segment" "test_segment_2" {
    display_name = "test_2"
    description = "tf provisioned test networking segment"
    connectivity_path = data.nsxt_policy_tier1_gateway.cgw.path
    transport_zone_path = data.nsxt_policy_transport_zone.cgw_transport_zone.path

    subnet {
        cidr = "192.168.215.1/24"
    }
}
```

Produces the following segment, as shown in the VMC on AWS NSX-T Networking Console:

![image](https://user-images.githubusercontent.com/50925498/97053694-67075480-1551-11eb-97cd-b226aa97d166.png)

VMC support has indicated that this type of segment is currently unsupported for general use in VMC SDDCs. For the segment to be supported, the type should be `Routed`. I can provide transcripts of my chat w/ VMC support if needed.

**Comment by dragoshaidet2** [comment]
+1 on fixing this issue

**Comment by tvigneron** [comment]
Hello,
There are two types of segment in NSX-T (and in VMConAWS).
The generic segment which is under /policy/api/v1/infra/segments/ which has a lifecycle on its own and the fixed segment which is a sub-object of the Tier-1 router which is used by VMC UI : /policy/api/v1/infra/tier-1s/<tier-1-id>/segments/<segment-id>
Terraform creates the first one today, which is available from API in VMC. This resource and the Terraform Provider have been validated by the VMC networking testing team. Resources validated and tested for VMC are here: (https://registry.terraform.io/providers/vmware/nsxt/latest/docs/guides/vmc) .

Now the VMC UI currently offers edit only on the fixed segment, not on the generic one.  So the segment created by Terraform cannot be edited from the UI currently  (more generally Terraform object should be edited from Terraform not the UI)
We are looking into adding another resource to cover the fixed segment for the VMC use-case, however that does not mean current Terraform usage creating generic segment is unsupported. 
Please reach out to me with the transcript if required (tvigneron@vmware.com), I'll add the VMC Networking PM and clarify this.

**Comment by annakhm** [comment]
Hi all, we added a dedicated `nsxt_policy_fixed_segment` to address this issue
