### ISSUE TITLE
nsxt_policy_vm_tags.k8s_nodes fails to apply tags

### ISSUE THREAD

**Issue by Sonic-Pancake** [vmware/terraform-provider-nsxt#494]
I'm using nsxt_policy_vm_tags.k8s_nodes to apply tags to the ports of k8s VM's so that the VMware NCP plugin will work correctly.

This is the code block to apply the tags.
```
resource "nsxt_policy_vm_tags" "k8s_master" {
  for_each    = toset(local.mstr_names)
  instance_id = vsphere_virtual_machine.k8s_master[each.value].id
  port {
    segment_path = data.nsxt_policy_segment_realization.k8s_data.path
    tag {
      tag   = each.value
      scope = "ncp/node_name"
    }
    tag {
      tag   = "k8s-${var.k8s_cluster_name}"
      scope = "ncp/cluster"
    }
  }
}
```
For some reason, most of the time tags are not applied but sometimes the tags apply. I believe it's a timing issue.
In my last deployment I deployed 4 VM's and only one got the tags. When I ran terraform again it applied the rest.
```
  # nsxt_policy_vm_tags.k8s_nodes["k8s-devnode2"] must be replaced
-/+ resource "nsxt_policy_vm_tags" "k8s_nodes" {
      ~ id          = "501b0ff7-ee4a-7eaf-e732-5025bd05f3cc" -> (known after apply)
        instance_id = "421bbeee-361f-f732-103a-1b154520886a"

      + port {
          + segment_path = "/infra/segments/18c92928-6f5d-492d-bb71-13289f45d271" # forces replacement

          + tag {
              + scope = "ncp/cluster"
              + tag   = "k8s-dev"
            }
          + tag {
              + scope = "ncp/node_name"
              + tag   = "k8s-devnode2"
            }
        }
    }
```
Am I missing a dependency, is this a bug or is nsxt_policy_vm_tags not waiting for segment_path or checking that correctly. 

My current work around is to run terraform again but if it's run before the VM has completed scripts it causes other issues but that's outside the scope of this provider.

If you need me to test anything let me know but at this stage it appears to be a bug.

**Comment by annakhm** [comment]
Hi @Sonic-Pancake, I believe the problem here is that `data.nsxt_policy_segment_realization.k8s_data.path` is known when the realization data source is not yet resolved, so terraform would not actually wait for realization to happen. I would suggest adding an explicit depends_on clause in nsxt_policy_vm_tags resource: 

> depends_on = [data.nsxt_policy_segment_realization.k8s_data] 

You should be able to see in the logs whether the tags starts resolving only after realization data source is done.

**Comment by Sonic-Pancake** [comment]
Thanks @annakhm for replying. I updated my terraform code to induce your suggestion of the depends on. Unfortunately upon testing the code again I couldn't reliably get the tags to apply. Some times they would and other times they wouldn't. I did capture the debug terraform logs. Is that what you need to look into this issue or is there more specific data I can collect?

**Comment by annakhm** [comment]
Hi @Sonic-Pancake, are the VMs you wish to be tagged applied as part of same terraform config? If yes, these should be included in depends_on as well.
