### ISSUE TITLE
Support "scope" for static routes, T0-VRF, VRF leaking use case

### ISSUE THREAD

**Issue by ipirva** [vmware/terraform-provider-nsxt#537]
I am interested in one specific case support: route leaking between VRFs with static routing
In NSX-T this is supported under T0-VRF / Routing / Static Routes

The static route would have:
- Name
- Network (destination)
- Next hops

This issue is to support "Scope" definition per Next hop, i.e. the VRF name under which the Next hop IP resides.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/17640388/102493871-1c4b1a00-4074-11eb-9fc8-c94d36853d6d.png">

**Comment by annakhm** [comment]
Hi @ipirva, this is already implemented as `interface`: https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_static_route#interface

I'll be clarifying in the docs that this is called `scope` in UI
