### ISSUE TITLE
T0 "EVPN Settings" support for VRF-lite

### ISSUE THREAD

**Issue by ipirva** [vmware/terraform-provider-nsxt#538]
When one configures VRF-lite with MP-BGP EVPN control plane, there is the need to choose or configure some "EVPN Settings"  at the T0 level:
- EVPN Mode
- EVPN/VXLAN VNI Pool
- EVPN Tunnel Endpoint 

EVPN Mode: choose between available modes, available on NSX-T platform
EVPN/VXLAN VNI Pool: choose an existing one or define one
EVPN Tunnel Endpoint: 1 per edge path per locale service

The support of these bits will allow enabling a T0 for MP-BGP EVPN and VXLAN data path.

Thank you.

**Comment by annakhm** [comment]
Thanks @ipirva, these are already on the roadmap

**Comment by ipirva** [comment]
Hello, 
How can I follow the progression of this ? Could you please share a link/issue/pr?

Thank you.

**Comment by annakhm** [comment]
Hello @ipirva, we started working on EVPN support. Linking the PRs here.
