### ISSUE TITLE
nsxt_policy_gateway_route_map using as_path_prepend set action only accepting 32bit numbers

### ISSUE THREAD

**Issue by wrightng** [vmware/terraform-provider-nsxt#569]
When trying to set a route map with AS prepends the provider appears to only accept 32bit numbers as seen below.

Error: 32bit number is expected, got 65204 65204
  on Zone1.tf line 320, in resource "nsxt_policy_gateway_route_map" "AAA_XXX_Prod_T0_DCI_UPLIFT":
 320:             as_path_prepend = "65204 65204"

This limits the ability to append multiple AS numbers and also limits the range of 4 Byte AS numbers that can be used.

**Comment by wrightng** [comment]
Additionally using
resource "nsxt_policy_gateway_route_map" "AAA_OMA_Prod_T0_DCI_UPLIFT" {
    display_name = "AAA_OMA_Prod_T0_DCI_UPLIFT"
    description  = "AAA OMA Prod Tier-0 DCI UPLIFT"
    gateway_path = nsxt_policy_tier0_gateway.AAA_OMA_Prod_T0.path

    entry {
        action              = "PERMIT"
        prefix_list_matches = [nsxt_policy_gateway_prefix_list.AAA_OMA_Prod_T0_All_subnets.path]

        set {
            as_path_prepend = 65204
        }
    }
}

with as_path_prepend value either quoted or left as numeric results in the provider running succesfully and creating the route map but the as path prepend value is not populated.

**Comment by annakhm** [comment]
Hello @wrightng, dotted notation should work for you, like "65204.65204".

**Comment by annakhm** [comment]
Closing this with above comment in mind, please reopen if needed!
