### ISSUE TITLE
nsxt_transport_zone

### ISSUE THREAD

**Issue by sba30** [vmware/terraform-provider-nsxt#573]
Hi, reading through the documentation -https://registry.terraform.io/providers/vmware/nsxt/latest/docs, cannot see a resource to create a nsxt_transport_zone.

Can see a datasource for this. Would this resource be called something else? or is it just not available?

Thanks

**Comment by annakhm** [comment]
Hello @sba30, fabric resources are not available at the moment

**Comment by sba30** [comment]
Will these fabric resources be available in the future?

**Comment by annakhm** [comment]
Its on the roadmap, but unfortunately not expected in next release.
