### ISSUE TITLE
creating a org network using "imported" network type option in vDC

### ISSUE THREAD

**Issue by cemkayar** [vmware/terraform-provider-nsxt#574]
A segment was created in NSX-T in order to use as a external org network under org vDC. 
I able to create it as a org network using "imported" (This type of network uses an existing NSX-T logical switch.) network type option via UI. 
Provider is supporting 3 resources (vcd_network_isolated, vcd_network_routed, vcd_nsxt_edgegateway) in order to create org network but none of them make what I need. Is there any way to use (with terraform) a org network created as segment in NSX?

**Comment by annakhm** [comment]
Hi @cemkayar, I don't have enough knowledge about vcd, but from their docs it looks like https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/external_network_v2 might be the resource you need.

**Comment by cemkayar** [comment]
To use vcd_external_network_v2, it must have a T0 or T1 router. But our design has none.
In order to be more understandable, I kindly ask you to browse the "vCloud Director OVDC configuration steps" topic in the link below.

https://www.evoila.de/en/blog/2020/04/16/vcloud-director-10-nsx-t-backed-ovdc-add-externel-based-network-with-dedicated-physical-nic/
