### ISSUE TITLE
Is logical DHCP server resource supported along with policy ones? 

### ISSUE THREAD

**Issue by mazzy89** [vmware/terraform-provider-nsxt#583]
I'm running NSX-T 2.5 and as reported in the doc the resource `nsxt_policy_dhcp_server` is not supported in the version prior to NSX-T 3.0.0.

I would then need to create a DHCP server with the logical resources like the following

```hcl
resource "nsxt_dhcp_server_profile" "server_profile" {
  edge_cluster_id = data.nsxt_policy_edge_cluster.edge_cluster.id
}

resource "nsxt_logical_dhcp_server" "dhcp_server" {
  display_name = "dhcp-server"

  dhcp_profile_id = nsxt_dhcp_server_profile.server_profile.id

  dhcp_server_ip = "10.10.0.2/16"
}

resource "nsxt_logical_dhcp_port" "dhcp_port" {
  admin_state  = "UP"
  display_name = "dhcp-port"

  logical_switch_id = nsxt_policy_segment.vmnet1.id
  dhcp_server_id    = nsxt_logical_dhcp_server.dhcp_server.id
}
```

However the creation of the resource `nsxt_logical_dhcp_port.dhcp_port` fails because of a 404 error returned. My gut feeling is that the `logical_switch_id` is not found because the policy segment id `nsxt_policy_segment.vmnet1.id` is passed. I believe this mixed up is not supported.

Is there a way to mix up the creation of DHCP server along with policy resources?

**Comment by tvigneron** [comment]
The nsxt_policy_segment.vmnet1.id is not the logical_switch_id, one is the policy path while the other is a uuid
I don't think there is a way to mix those from Terraform, as you need to map to logical switch id to the policy segment.
I'm sorry but I don't think there's a good solution except update NSX-T to 3.X

**Comment by mazzy89** [comment]
Thanks a lot @tvigneron to reply to this very quick.

Yes this is what I was afraid. Wouldn't be a way to query the policy segment and retrieve the logical switch Id? Perhaps not by  terraform buy using an http request and retrieve that ID. Asking.

**Comment by tvigneron** [comment]
In the API you have system generated setting called unique_id on the segment. 
This is a uuid and would be this logical switch id.

**Comment by mazzy89** [comment]
I see. Then I think it would not be too hard to expose also this unique_id in the output of the resource so we can use it. I might wire a PR for this. What do you think?

**Comment by tvigneron** [comment]
The issue I see is the dependency between MP and Policy. We are modifying a Policy resource  by attaching something it doesn't know to it, this can lead to multi-master issues. I don't know how well it would play with Terraform managing all that.

**Comment by mazzy89** [comment]
I'm not very navigated here to the API structure of NSX-T. Do you think is something that can be explored deeper in a feature request? Do you think there is a sense to do so? 

Meanwhile to mitigate this issue I will just query the API manually perhaps using an http terraform provider and fetch that ID

**Comment by mazzy89** [comment]
I've tried also to get the `unique_id` via https://kb.vmware.com/s/article/79872#Getting_LogicalSwitch_UUID_from_NSX-API but in the response, I did not find any `unique_id` field. I'm quite confused here.

**Comment by tvigneron** [comment]
I checked and this unique_id is not there in 2.5..
Sorry I was playing with my 3.1.1 version : https://code.vmware.com/apis/1124/nsx-t 
It is not : https://code.vmware.com/apis/892/nsx-t

**Comment by mazzy89** [comment]
I see. Now it makes sense. Do you see other ways to get the logical switch uuid from a segment in the 2.5 API?

**Comment by annakhm** [comment]
Hi @mazzy89, please check out https://registry.terraform.io/providers/vmware/nsxt/latest/docs/data-sources/policy_realization_info#realized_id, I believe this is what you're looking for.

**Comment by mazzy89** [comment]
Hi @annakhm Thanks a lot 

```hcl
data "nsxt_policy_realization_info" "segment_info" {
  path = nsxt_policy_segment.vmnet1.path
  entity_type = "RealizedLogicalSwitch"
}
```

This data resource solved the problem in a very elegant way still using Terraform and avoiding upgrading. Very appreciate your help here. 😊

I'm going to close the issue here..
