### ISSUE TITLE
Allow IP Address, CIDR, Range, or "ANY" as source_groups or destination_groups in nsxt_policy_security_policy resource

### ISSUE THREAD

**Issue by akgiesler** [vmware/terraform-provider-nsxt#584]
The NSX-T API allows setting the source_groups and/or destination_groups of a Distributed firewall policy to an NSGroup, IP, IP Range, CIDR, or the "ANY" keyword.  This can also be accomplished in the policy UI and was tested in NSX-T v3.1.

The schema for the rules object in NSX-T 3.1 can be found [here](https://vdc-download.vmware.com/vmwb-repository/dcr-public/787988e9-6348-4b2a-8617-e6d672c690ee/a187360c-77d5-4c0c-92a8-8e07aa161a27/api_includes/types_Rule.html).

It appears that [the nsxt_policy_security_policy resource](https://github.com/vmware/terraform-provider-nsxt/blob/master/nsxt/resource_nsxt_policy_security_policy.go) is enforcing the source_groups and destination_groups fields to be paths to NSgroups.  Link to the group validation is [here](https://github.com/vmware/terraform-provider-nsxt/blob/7860cf208555092647544be0ba7217da4ec00da6/nsxt/policy_utils.go#L160). Could this be adjusted to match the API?

**Comment by annakhm** [comment]
This is now addressed, thanks to @akgiesler

**Comment by AlexDias95** [comment]
@annakhm 
Version 3.1.1 of the provider allow the use of IP CIDR in the destination groups? Thx for the help!
