### ISSUE TITLE
Error: Failed to read Groups (Error unmarshalling server response) when trying to retrieve VMC policy groups  

### ISSUE THREAD

**Issue by sonofaloop** [vmware/terraform-provider-nsxt#592]
I am looking to use Terraform to configure firewall policies in my VMware Cloud on AWS SDDC but have an intermittent issue when trying to retrieve data for nsxt_policy_groups defined outside my project.   I'm quite new to Terraform so apologies if I haven't provided all the information you require upfront.

The idea is to lookup up existing policy groups via a variable list so that I can reference the paths elsewhere in my config.  I'm using for_each to loop through the results which might be the issue but like I say it works as expected some of the time (most of the time if there are only a few data blocks).

My config works but I have found that the more data sources I add the more likely it is I will receive the following error -   Error: Failed to read Groups (Error unmarshalling server response) when trying to retrieve multiple policy group data sources.

An example of my config is below.  Currently I have 8 similar data blocks in my config and I find that my plan works fine the first time and then if I try again a few minutes later I receive the error. 

variable "db_server_sddc_groups_in" {
  type = set(string)
    default = ["PDT.ABC.APP.PROD","PDT.ABC.WEB.PROD"]
}

data "nsxt_policy_group" "db_server_sddc_groups_in" {
 for_each = var.db_server_sddc_groups_in
 display_name = each.value
 domain = "cgw"
}

And the output to show that I am succesfully presenting the path back to other resources:

output "db_server_sddc_groups_in" {
   value = [for group in data.nsxt_policy_group.db_server_sddc_groups_in: group.path]

Debug output...

2021-03-17T13:29:18.862Z [DEBUG] plugin.terraform-provider-nsxt_v3.1.1.exe: 2021/03/17 13:29:18 Error unmarshalling server response
2021/03/17 13:29:18 [ERROR] eval: *terraform.evalReadDataRefresh, err: Failed to read Groups (Error unmarshalling server response)
2021/03/17 13:29:18 [ERROR] eval: *terraform.EvalSequence, err: Failed to read Groups (Error unmarshalling server response)
2021/03/17 13:29:18 [TRACE] [walkRefresh] Exiting eval tree: data.nsxt_policy_group.db_server_sddc_groups_in["PDT.ABC.APP.PROD"]
2021/03/17 13:29:18 [TRACE] vertex "data.nsxt_policy_group.db_server_sddc_groups_in[\"PDT.ABC.APP.PROD\"]": visit complete
2021/03/17 13:29:18 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/03/17 13:29:18 [TRACE] vertex "data.nsxt_policy_group.db_server_sddc_groups_in": dynamic subgraph encountered errors
2021/03/17 13:29:18 [TRACE] vertex "data.nsxt_policy_group.db_server_sddc_groups_in": visit complete
2021/03/17 13:29:18 [TRACE] vertex "data.nsxt_policy_group.db_server_sddc_groups_in (expand)": dynamic subgraph encountered errors
2021/03/17 13:29:18 [TRACE] vertex "data.nsxt_policy_group.db_server_sddc_groups_in (expand)": visit complete

**Comment by annakhm** [comment]
Hello @sonofaloop, this issue is due to "proxy timeout" error issued by VMC proxy. Unfortunately the provider fails to parse it since it comes back in XML rather than JSON. 
A possible workaround is to use direct VMC connection (bypassing the proxy) if that's an option for you. (See more here https://registry.terraform.io/providers/vmware/nsxt/latest/docs#vmc_auth_mode)
