### ISSUE TITLE
IP Pool Subnet and Gateway

### ISSUE THREAD

**Issue by reneherrero** [vmware/terraform-provider-nsxt#600]
Hi,

I'm able to use the provider to assign an IP like this:
```
data "nsxt_policy_ip_pool" "pool" {
  display_name = "IPAM-POOL"
}

resource "nsxt_policy_ip_address_allocation" "ipam_pool" {
  display_name = "ip-rene-vm-1"
  pool_path    = data.nsxt_policy_ip_pool.pool.path
}
```

then, reference the resource as such:
```
      network_interface {
        ipv4_address = nsxt_policy_ip_address_allocation.ipam_pool.allocation_ip
        ipv4_netmask = "27"
      }
      ipv4_gateway = "192.168.1.1"
```

Question: How could I auto-populate the ipv4_netmask and ipv4_gateway fields? (those values are in NSX-T)

Thanks!

**Comment by salv-orlando** [comment]
Subnet prefix and gateway are not part of the IPallocation object. If the segment has a subnet configured, it will be possible to extract the gateway address from the segment information.
For the prefix, it can either be extracted from the gateway address, which is in CIDR notation, or from the IP Pool (if there is one attached to the segment).

Closing this issue as it won't be possible to implement this enhancement as a part of the IP allocation resource.
