### ISSUE TITLE
Add functionality to nsxt_policy_group to include Tag Scope in Condition

### ISSUE THREAD

**Issue by jjahns** [vmware/terraform-provider-nsxt#601]
In the event that a record has the following tag configuration:

Tag Scope: AppName
Tag: Abc

Tag Scope: Realm
Tag: Abc

The resource nsxt_policy_group does not allow the specification of tag scope, similar to that of the UI. This could be problematic if there are NSGroups that need to use both tag criteria as a condition, and cannot because they are both the same, or end up matching both scopes.

This needs to be added in order to address this problem moving forward.

**Comment by annakhm** [comment]
Hi @jjahns, scope can be specified using `|` notation: https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_group#value
