### ISSUE TITLE
Policy API support for logical router

### ISSUE THREAD

**Issue by a-dawg** [vmware/terraform-provider-nsxt#606]
### Versions
nsxt: 3.1.1
nsxt provier: 3.1.1
terraform: 0.14

### Issue
when trying to create the below resource, it does not appears into the policy view but in the manager view in the nsxt gui. 

I suspect then that the provider uses the legacy nsxt API instead of the policy API, is that correct? The docs seems to say that the provider the support the policy API, is that the case for this resource? Is it something that will be changed in the next releases?

```
resource "nsxt_logical_tier1_router" "tier1_router" {
  description                 = "RTR1 provisioned by Terraform"
  display_name                = "RTR1"
  failover_mode               = "PREEMPTIVE"
  edge_cluster_id             = data.nsxt_policy_edge_cluster.Edge-Cluster.id
  enable_router_advertisement = true
  advertise_connected_routes  = false
  advertise_static_routes     = true
  advertise_nat_routes        = true
  advertise_lb_vip_routes     = true
  advertise_lb_snat_ip_routes = false
}
```

**Comment by kalenarndt** [comment]
@a-dawg you are using the manager resource call instead of the policy one. Modify yours to use the one below.

https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_tier1_gateway

**Comment by annakhm** [comment]
@a-dawg legacy resources still exist in provider, though these will be deprecated at some point. Please use resources and data sources that start with `policy_` (and listed under `Policy` sections in the docs)

**Comment by a-dawg** [comment]
thanks much! Apologies for misreading the docs
