### ISSUE TITLE
Data source for nsxt_policy_lb_service

### ISSUE THREAD

**Issue by pezhore** [vmware/terraform-provider-nsxt#618]
I'm trying to create a new virtual server on an existing LB, but it looks like there isn't a `data_source_nsxt_policy_lb_service` resource available.

I can just copy/paste from the UI, but is there a programmatic way of retrieving this path without the data source?

Expected behavior:

```hcl
data "nsxt_policy_lb_service" "existing" {
   display_name  = "Existing LB"
}

resource "nsxt_policy_lb_virtual_server" "test" {
  display_name = "Terraform Test"
  description = "Terraform provisioned virtual server"
  application_profile_path = data.nsxt_policy_lb_app_profile.app.path
  ip_address = "10.0.0.20"
  service_path = data.nsxt_policy_lb_service.existing.path
  ports = ["80"]
}
```

**Comment by annakhm** [comment]
Hi @pezhore, there is no such feature today - please use policy path as string. Marking as enhancement.

**Comment by annakhm** [comment]
This data source [exists ](https://github.com/vmware/terraform-provider-nsxt/blob/master/nsxt/data_source_nsxt_policy_lb_service.go) today, hence closing this.
