### ISSUE TITLE
lifecycle / ignore_changes / ns_group members as list

### ISSUE THREAD

**Issue by arothste-blk** [vmware/terraform-provider-nsxt#635]
- In the situation where the members of an [ns_group](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/ns_group) are managed outside of Terraform, I'm trying to tell Terraform to [ignore_changes](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes) on the "member" attribute. That attribute is a list and I don't think it's working in terraform:0.15.5.
- The code looks like this
```
resource "nsxt_ns_group" "concourse_ns_group" {
  display_name = "${var.environment_name}_concourse_ns_group"

  lifecycle {
    ignore_changes = [member]
  }

  tag {
    scope = "terraform"
    tag   = var.environment_name
  }
}
```
- The plan currently looks like this
```
   ~ resource "nsxt_ns_group" "concourse_ns_group" {
         id           = "id1"
       ~ revision     = 3 -> 6
         # (1 unchanged attribute hidden)
       + member {
           + target_type = "LogicalPort"
           + value       = "lp1"
         }
       + member {
           + target_type = "LogicalPort"
           + value       = "lp2"
         }
       + member {
           + target_type = "LogicalPort"
           + value       = "lp3"
         }
         # (4 unchanged blocks hidden)
     }
```
- `lp1`, `lp2`, and `lp3` are the appropriate logical ports to have in the group so I'm not expecting an outage should I apply this change
- It doesn't look like the `ignore_changes` is working on `member`. I'm guessing because it's a list though I have no proof.

This problem originates from the VMWare recommended virtual network paving for BOSH based Concourse deployments on [vSphere+NSX-T](https://docs.pivotal.io/p-concourse/v6/installation/install-platform-automation/)

**Comment by annakhm** [comment]
Looks like this issue with `ignore_changes` was fixed a while back in terraform and should work with your version: https://github.com/hashicorp/terraform/issues/21421
Beware that `lifecycle` should be present on resource creation, otherwise its not catching.
