### ISSUE TITLE
nsxt_policy_gateway_route_map usage documentation mistake

### ISSUE THREAD

**Issue by akhomyakov** [vmware/terraform-provider-nsxt#638]
It appears that the example doesn't match the reference docs below it
The example shows `match_operator = "MATCH_COMMUNITY_REGEX"`, however, the reference guide below it mentioned `COMMUNITY_REGEX`, i.e without the word `MATCH_`.

"community_list_match - (Optional) List of Prefix List match criteria for route map" phrase just seems like a copy/paste typo in that it is saying that community_list is a list of prefix_lists. That doesn't make any sense.

**Comment by annakhm** [comment]
@akhomyakov thanks for reporting this!
