### ISSUE TITLE
[BUG] Unable to enable T0 VRF BGP

### ISSUE THREAD

**Issue by vfuyong** [vmware/terraform-provider-nsxt#646]
Provider version: 3.2.2 (latest)

resource "nsxt_policy_bgp_config" "config" {
  gateway_path    = nsxt_policy_tier0_gateway.gw1.path
  enabled         = true
  ecmp            = true
}

As far as I understand, only "enabled" and "ecmp" need to be specified. 

Here is the output:

Error:  Failed to create BgpRoutingConfig: Only ecmp, enabled, BGP Aggregate to be configured for VRF BGP Config. (code 503175)

**Comment by benohara** [comment]
seeing the same

**Comment by fgrehl** [comment]
Same problem with 3.2.4.
I think it tries to set default BGP timers (graceful_restart_timer, graceful_restart_stale_route_timer) when you do not set them in the resource. When TF communicates with the NSX-T API, it must not set those. It will automatically inherit parent Tier-0 timers.
