### ISSUE TITLE
nsxt_policy_dhcp_relay support on global manager

### ISSUE THREAD

**Issue by jamiegrandfield** [vmware/terraform-provider-nsxt#649]
Feature request.  It seems the resource nsxt_policy_dhcp_relay does not work correctly if connected to a global manager.

Scenario -
NSX-T 3.1.2.1

```
terraform {
  required_providers {
    nsxt = {
      source  = "vmware/nsxt"
      version = "3.2.2"
    }
  }
}

provider "nsxt" {
  host                  = "myglobalmanager.domain.tld"
  username              = "admin"
  password              = "password"
  allow_unverified_ssl  = true
  max_retries           = 10
  retry_min_delay       = 500
  retry_max_delay       = 5000
  retry_on_status_codes = [429]
  global_manager        = true
}

resource "nsxt_policy_dhcp_relay" "infoblox" {
  display_name     = "infoblox"
  server_addresses = ["10.1.0.10", "10.2.0.10"]
}
```

Actual error received -
```
nsxt_policy_dhcp_relay.infoblox: Creating...
╷
│ Error:  Failed to create DhcpRelayConfig 1cd3e5ef-f0d7-4874-a157-f6ef470c9c33: Cannot connect to server (code 98)
│
│   with nsxt_policy_dhcp_relay.infoblox,
│   on 3 - dhcp.tf line 7, in resource "nsxt_policy_dhcp_relay" "infoblox":
│    7: resource "nsxt_policy_dhcp_relay" "infoblox" {
│

```

**Comment by himanshu007-creator** [comment]
Hi, I would like to work on this issue?
Can you elaborate on what needs to be done ^_^?

**Comment by jamiegrandfield** [comment]
I can't comment myself on the details of the implementation, but the ask is for support for the ability to create nsxt_policy_dhcp_relay resources on a global manager.  I'm not sure if this is related, but the URI for doing this on a global manager is slightly different compared to a local manager.

Local manager URI - PATCH /policy/api/v1/infra/dhcp-relay-configs/<dhcp-relay-config-id>
Global manager URI - PATCH /policy/api/v1/global-infra/dhcp-relay-configs/<dhcp-relay-config-id>

**Comment by annakhm** [comment]
Hello, I apologize for not noticing the comments here earlier, and also the bot behavior :)
Indeed dhcp relay support on Global Manager is still missing. We welcome contributions on this - this resource https://github.com/vmware/terraform-provider-nsxt/blob/master/nsxt/resource_nsxt_policy_dhcp_server.go can serve as an example.
