### ISSUE TITLE
Inconsistent policy at rule scope

### ISSUE THREAD

**Issue by benohara** [vmware/terraform-provider-nsxt#654]
I create a nsxt_policy_nat_rule, passing in the scope (paths to interfaces to apply one)

This creates and add the following to the state

    resource "nsxt_policy_nat_rule" "customer_mgmt_snat" {
        action               = "SNAT"
        description          = "Terraform provisioned NAT Rule for custc"
        destination_networks = [
            "100.100.3.0/24",
        ]
        display_name         = "SNAT2CUSTC"
        enabled              = true
        firewall_match       = "MATCH_INTERNAL_ADDRESS"
        gateway_path         = "/infra/tier-0s/gen3-tm-mgmt-t0-gw"
        id                   = "beca2ba5-7604-410d-8054-4118ec9e1e77"
        logging              = false
        nsx_id               = "beca2ba5-7604-410d-8054-4118ec9e1e77"
        path                 = "/infra/tier-0s/gen3-tm-mgmt-t0-gw/nat/USER/nat-rules/beca2ba5-7604-410d-8054-4118ec9e1e77"
        revision             = 0
        rule_priority        = 100
        scope                = [
            "/infra/tier-0s/gen3-tm-mgmt-t0-gw/locale-services/default/interfaces/b5019fb1-3045-4c91-b822-e36c3d517b92",
            "/infra/tier-0s/gen3-tm-mgmt-t0-gw/locale-services/default/interfaces/958f25d2-5ff1-44db-87ee-f0ac16b68fbc",
        ]
        translated_networks  = [
            "100.100.3.1",
        ]

    }

In the scope, b501 is int02 and 958 is int01,

The policy nat resource creation passes in
scope  = nsxt_policy_tier0_gateway_interface.customer_uplink_interfaces.*.path

Now on a subsequent run, terraform is going to change the order of the scope.  This applies, but the next run changes it again.

Suspect NSX is giving these back ordered based on the uuid?

Am i missing something in how i create the nat rule or is this a bug in the provider?

**Comment by annakhm** [comment]
Hi @benohara, thanks for reporting this, look like a bug in scope definition. Can you please report what your NSX version is? Thanks!

**Comment by benohara** [comment]
Hi @annakhm this is with NSX-T 3.1.2.0.0.17883600

Cheers
Ben

**Comment by annakhm** [comment]
Thanks @benohara, as a workaround you can change the order of scopes in your config. On our side, we'll be changing the scope type to avoid order enforcement.
