### ISSUE TITLE
Deleting Firewall policy fails due to dependency.

### ISSUE THREAD

**Issue by sentania** [vmware/terraform-provider-nsxt#658]
I have a firewall policy that consists of group definition, a service definition, and a rule definition, as seen [here](https://github.com/sentania/nsx_terraform_security/commit/853b6043fa7bfcd1be42aeb8ba9f30f69c995113#diff-db3ec5a10adada0cd0bb8e2144563281cc35303bf241bdc4b8d4b9e0b1e9e022)

> ####Allow RDP
> resource "nsxt_policy_group" "AllowRDP" {
>   display_name = "Allow RDP"
>   description  = "Allow RDP Group provisioned by Terraform"
>   criteria {
>       condition {
>           key         = "Tag"
>           member_type = "SegmentPort"
>           operator    = "EQUALS"
>           value       = "AllowRDP|Role"
>       }
>     }
>     tag {
>         scope = "AllowRDP"
>         tag   = "Role"
>     }
> }
> 
> resource "nsxt_policy_service" "RDPService" {
>   description  = "RDP Serivces provisioned by Terraform"
>   display_name = "RDP Services"
> 
>   l4_port_set_entry {
>     display_name      = "RDP Server Services"
>     description       = "TCP port 3389"
>     protocol          = "TCP"
>     destination_ports = [ "3389" ]
>   }
> }
> 
> ###END RDP Delcaration
> ++++++++++++++++++++++++++
> resource "nsxt_policy_security_policy" "PrivateCloudPolicies" {
>   description  = "Private Cloud Blueprint Policies Section provisioned by Terraform"
>   display_name = "Private Cloud Blueprint Policies"
>   category = "Application"
>   rule {
>     display_name = "Web Traffic"
>     description  = ""
>     action       = "ALLOW"
>     ip_version  = "IPV4"
>     services = [nsxt_policy_service.WebServerServices.path]
>     destination_groups = [nsxt_policy_group.WebServers.path]
>     scope = [nsxt_policy_group.WebServers.path]
>   }
>     rule {
>     display_name = "MySQL Traffic"
>     description  = ""
>     action       = "ALLOW"
>     ip_version  = "IPV4"
>     services = [nsxt_policy_service.MySQLServices.path]
>     source_groups = [nsxt_policy_group.MySQLClients.path]
>     destination_groups = [nsxt_policy_group.MySQLServers.path]
>     scope = [nsxt_policy_group.MySQLClients.path,nsxt_policy_group.MySQLServers.path]
>   }
> 
>     rule {
>     display_name = "MySQL Traffic"
>     description  = ""
>     action       = "ALLOW"
>     ip_version  = "IPV4"
>     services = [nsxt_policy_service.MSSQLServices.path]
>     source_groups = [nsxt_policy_group.MSSQLClients.path]
>     destination_groups = [nsxt_policy_group.MSSQLServers.path]
>     scope = [nsxt_policy_group.MySQLClients.path,nsxt_policy_group.MySQLServers.path]
>   }
> 
>     rule {
>     display_name = "SSH Traffic"
>     description  = ""
>     action       = "ALLOW"
>     ip_version  = "IPV4"
>     services = [nsxt_policy_service.SSHService.path]
>     destination_groups = [nsxt_policy_group.AllowSSH.path]
>     scope = [nsxt_policy_group.AllowSSH.path]
>   }
>     rule {
>     display_name = "RDP Traffic"
>     description  = ""
>     action       = "DROP"
>     ip_version  = "IPV4"
>     services = [nsxt_policy_service.RDPService.path]
>     destination_groups = [nsxt_policy_group.AllowRDP.path]
>     scope = [nsxt_policy_group.AllowRDP.path]
>   }
> }
> 

If I remove the group definition, service definition, and rule definition - a terraform apply fails with the following errors:

`Failed to delete Service 673ae1a0-942e-4432-9e43-54f851e6bbfd: The object path=[/infra/services/673ae1a0-942e-4432-9e43-54f851e6bbfd] cannot be deleted as either it has children or it is being referenced by other objects path=[/infra/domains/default/security-policies/ad0f309b-97c0-48fc-8fc1-cfe9451478c1/rules/9df12fd5-ea05-46ce-a5ee-a4ff4030cb09] (code 500030)`

`Failed to delete Group c8dee0ee-0626-46c1-b383-e389169d2160: The object path=[/infra/domains/default/groups/c8dee0ee-0626-46c1-b383-e389169d2160] cannot be deleted as either it has children or it is being referenced by other objects path=[/infra/domains/default/security-policies/ad0f309b-97c0-48fc-8fc1-cfe9451478c1/rules/9df12fd5-ea05-46ce-a5ee-a4ff4030cb09] (code 500030)`

Expected Behavior:
The group definition, service definition and rule definition should all be deleted.

@rpletka

**Comment by annakhm** [comment]
Hello @sentania, this looks like https://registry.terraform.io/providers/vmware/nsxt/latest/docs/guides/faq#dependency-error-nsx

**Comment by sentania** [comment]
So since in a pure devops model - simply rerunning the code/pipeline doesn't work - is the only answer right now to declare explicit dependencies in the policy_security_policy resource for the policy_service and policy_group resources that are referenced

**Comment by annakhm** [comment]
This should be solved with next release, since retries were added to both group and service deletion
