### ISSUE TITLE
Please add support Destination Protocol argument for nsxt_policy_gateway_redistribution_config resource

### ISSUE THREAD

**Issue by scila1996** [vmware/terraform-provider-nsxt#668]
Please add support optional for Destination Protocol. In VMware doc, it is not description about it, however, in NSX-T 3.1, it is necessary if I need to re-route from segment to T-0 -> OSPF/BGP. Please add support for it

![image](https://user-images.githubusercontent.com/17109300/132675130-d7247ae5-d495-4719-a926-a9d52e5f5275.png)

**Comment by annakhm** [comment]
Hello, the protocol indicators are called `bgp_enabled` and `ospf_enabled`:
https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_gateway_redistribution_config#bgp_enabled

Hope this helps!

**Comment by scila1996** [comment]
> Hello, the protocol indicators are called `bgp_enabled` and `ospf_enabled`:
> https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_gateway_redistribution_config#bgp_enabled
> 
> Hope this helps!

Thank for reply ! But trust me, I was passed VCP-NV and i know what exactly of VMware NSX-T 3.1, `bgp_enabled` and `ospf_enabled` optional refer to 'Global Status of BGP and OSPF', but inside `rule` argument, we have more than 10 redistribution types, and we need to config some type of them to only one routing protocol such BGP or OSPF. 

This bellow image describe about 'Global status' as they said. But in first comment with above image, it's `rule` with `redistribution types` and we need to map several `redistribution types` with only OSPF or BGP, that why we need to add `Destination Protocol` to `rule` argument


![image](https://user-images.githubusercontent.com/17109300/133191509-d4028d43-6623-4466-9f1a-002f7c20bd09.png)

**Comment by scila1996** [comment]
And one more thing. With redistribution rules, we can create maximum of 2 rule corresponding to OSPF rule and BGP rule. But with `nsxt_policy_gateway_redistribution_config`, it's only can have one default rule with "list of redistribution types". In my config in NSX-T 3.1, I can add two rule with some `redistribution types` will belong to `Destination Protocol` (OSPF/BGP)

![image](https://user-images.githubusercontent.com/17109300/133192465-d4426b76-652e-4c13-812c-7ec619212d5c.png)

**Comment by annakhm** [comment]
Thank you for the clarification @scila1996, I understand the ask now.
