### ISSUE TITLE
Add support for Edge VMs and Clusters

### ISSUE THREAD

**Issue by akhomyakov** [vmware/terraform-provider-nsxt#672]
Hi,
Would you, please, add support for instantiating and managing edge VMs and clusters? In the current state the rest of the features cannot be used until the edge clusters are instantiated.
In other words, operation teams might not be able to provision any of the T0s or T1 or load balancers due to not having an edge cluster to put them on thus making the cluster provisioning which is currently only possible via API and GUI a blocker for managing the rest of the constructs as code.

Thank you in advance,
Andrey

**Comment by scila1996** [comment]
I think edge node and edge cluster are not need for terraform. Current, it has only as datasources of Edge and Cluster, i totally agree that does not support resource for Edge VM and Cluster, many system use Edge bare-metal instead of Edge VM, second Edge VM are deployed on vCenter with complex configuration and relative to vCenter and them work as Edge network device system, used as North-sourth traffic and have little change about config, NSX-T is SDN Network solution, no need to configure too much on Edge Node, and it must be configured as hand way to full control system. But current, it is still support as DataSource, that's enough

https://registry.terraform.io/providers/vmware/nsxt/latest/docs/data-sources/policy_edge_node

**Comment by scila1996** [comment]
Another way, if you still want to use. You can try ansible nsx-t

https://github.com/vmware/ansible-for-nsxt

**Comment by akhomyakov** [comment]
I can see reason on that point of view, so I appreciate it. With that said let me try to expand on my reasoning.

Firstly, on the point of bare metal edges. Obviously those cannot be expected to be managed by terraform, and to your point, those are covered by the "data" resources and are already supported today.
The use case I'm describing is explicitly about the VM form factor. The trouble with edge VMs and clusters only being available as a "data" resource is that if my operator needs to create a new T0 or if the system ran out of load balancing capacity on the existing edge cluster, the operator now has to perform "out of band" (read outside of terraform) steps by either using APIs, GUI, or Ansible, and thus, the complete state of the system is not described in a single repository.

It is not critical, but perhaps ironic is that edge VMs will use TEP IPs out of IP pools that can be managed by terrafrom. In other words, in order for me to build an edge VM and cluster, I need to first apply a terraform state to instantiate the IP pools. Then I can instantiate the edge VMs and clusters only to have to import them into the terraform state as "data" resources.
My current solution is to have two separate terraform states: one just for "transport IP pools" and the other one "for everything else", which is not ideal.

I also fully grasp that maybe it's simply not viable to include edge vms as a resource in terraform as it takes good 20 min to instantiate a pair of edge VMs and cluster them  with APIs, but other than the time, it doesn't seem that complicated compared to what otherwise I'd have to do with pure APIs. Check out the number of API requests I have to execute to instantiate a 2 VM cluster. This can't be the experience VMware thinks is best for VMware's customers.
![Screen Shot 2021-09-15 at 9 28 30 AM](https://user-images.githubusercontent.com/16153883/133472664-8ee733f7-85ad-4dbd-ae15-9e073f9ace02.png)

I am currently debating if it's worth the effort to use something like a "local-exec" to instantiate the edge VMs as part of the terraform state, but that just seems like a terrible solution. It maybe fine if I know edge VM resources are on the road map for this provider, but I wouldn't say that's something I want to have as my permanent approach.

At the end of the day the trouble is that a single edge VM cluster has finite capacity for the resources managed with terraform and there is currently no way to extend that capacity within terraform (by instantiating additional clusters) and so the terraform operator will eventually be in a situation where they can no longer provision additional functionality without doing "out of band" provisioning work.

**Comment by scila1996** [comment]
So you need to "autoscale" Edge VM and thus, you need to have support of Edge Node/Cluster resource feature and when new edge vm are created, and you must be to create an ip pool for new Edge Node ?

 What version of NSX-T  you are using 2.5, 3.0, 3.1, they are different about feature and concept of TEP IP pool. With NSX-T 3.1 you can to config multiple TEP ip pool or single TEP ip pool with some only one subnet. Not worried about TEP IP pool

**Comment by annakhm** [comment]
Hello Andrey, we do plan to add support for fabric, including edge nodes and clusters, as part of the next development cycle (unfortunately I don't have the ETA yet). However, provisioning VMs themselves is not planned to be part of this provider (other providers such as https://github.com/hashicorp/terraform-provider-vsphere should be used to this purpose).  NSX configuration part of the edge VM (such as defining the IP Pool that you have mentioned) will hopefully be covered as part of the NSX provider. Hope this makes sense, and I'll update this issue when we have more clarity on the ETA.

**Comment by akhomyakov** [comment]
Hey folks. Thanks for the responses. Much appreciated. 
I am not trying to say the nsxt provider must manage the edge infrastructure, but rather I'm advocating for the nsxt infrastructure be managed in its entirety with terraform. So if I have to use the vsphere provider (or any other provider for that matter as long as I don't have to do it outside of terraform), that works for me as well. 
Another reason I entered this request is that there isn't one, so I figured I should at least request the feature to let you, folks, know that there is interest.
Cheers and keep up the good work.

**Comment by akhomyakov** [comment]
One more thing I discovered on the subject and perhaps that's something that is a bit easier to fix than adding a full blown support for edge clusters.
In order to cluster edge VMs one can use [POST /api/v1/edge-clusters](https://vdc-download.vmware.com/vmwb-repository/dcr-public/787988e9-6348-4b2a-8617-e6d672c690ee/a187360c-77d5-4c0c-92a8-8e07aa161a27/api_includes/system_administration_configuration_fabric_edge_clusters_edge_clusters.html) call. 
The API call instructs to submit "members" using [EdgeClusterMember schema](https://vdc-download.vmware.com/vmwb-repository/dcr-public/787988e9-6348-4b2a-8617-e6d672c690ee/a187360c-77d5-4c0c-92a8-8e07aa161a27/api_includes/schemas_EdgeClusterMember.html). 
Here is an example of a call I am making:
```
↳ Create Edge Cluster
  POST https://labnsx101.lab.athenahealth.com/api/v1/edge-clusters
  201 Created ★ 7.8s time ★ 801B↑ 1.57kB↓ size ★ 11↑ 17↓ headers ★ 0 cookies
  ┌ ↑ raw ★ 349B
  │ {
  │     "description": "Load Balanacing Edge Cluster 1",
  │     "members": [
  │         {
  │             "transport_node_id": "948ff44b-99d4-4d31-a636-2c56cee2a6f1"
  │         },
  │         {
  │             "transport_node_id": "d5f5d904-3f84-4e6a-b0fb-6ab787adabb5"
  │         }
  │     ],
  │     "resource_type": "EdgeCluster",
  │     "display_name": "BED-LAB-EDGE-CLUSTER-LB-1"
  │ }
  └
  ┌ ↓ application/json ★ text ★ json ★ utf8 ★ 953B
  │ {
  │   "deployment_type" : "VIRTUAL_MACHINE",
  │   "members" : [ {
  │     "member_index" : 0,
  │     "transport_node_id" : "948ff44b-99d4-4d31-a636-2c56cee2a6f1"
  │   }, {
  │     "member_index" : 1,
  │     "transport_node_id" : "d5f5d904-3f84-4e6a-b0fb-6ab787adabb5"
  │   } ],
  │   "cluster_profile_bindings" : [ {
  │     "resource_type" : "EdgeHighAvailabilityProfile",
  │     "profile_id" : "91bcaa06-47a1-11e4-8316-17ffc770799b"
  │   } ],
  │   "member_node_type" : "EDGE_NODE",
  │   "allocation_rules" : [ ],
  │   "enable_inter_site_forwarding" : false,
  │   "resource_type" : "EdgeCluster",
  │   "id" : "3cd4ca26-61ac-4c4d-bfd4-ba92ebb5d9e8",
  │   "display_name" : "BED-LAB-EDGE-CLUSTER-LB-1",
  │   "description" : "Load Balanacing Edge Cluster 1",
  │   "_create_user" : "<snip>",
  │   "_create_time" : 1632354365103,
  │   "_last_modified_user" : "<snip>",
  │   "_last_modified_time" : 1632354365103,
  │   "_system_owned" : false,
  │   "_protection" : "NOT_PROTECTED",
  │   "_revision" : 0
  │ }
  └
```
The trouble is that the `transport_node_id` specified first does not seem to reliably end up being given member index 0.
I am finding that for some reason even though `948ff44b-99d4-4d31-a636-2c56cee2a6f1` is specified first in the "members" hash, it ends up being index member 1.
There seems to be no way to control that within the POST call.

Now when we go to import the cluster members using the nsxt_policy_edge node resource, there is no way to specify anything other than member's index. And thus while I expect a particular edge VM uuid to be returned as the uuid of the member 0, I cannot guarantee that it will always be the first UUID specified in the POST /api/v1/edge-clusters.

This has cascading consequences down the line because I have to place certain resources onto specific edge VMs (in our case edge VMs are in different subnets, so when I declare an interface on a gateway, I must place it onto the correct VM. If those are swapped, I end up with a non functioning T0 interfaces.

Perhaps there is a way to add something to the data_nsxt_policy_edge resource to be a bit more deterministic in which edge node gets imported? I.e. maybe there is a way to import based on the display name or something like that rather than just on index alone?

Unfortunately, in the above example, the index assignment ended up ordered as submitted. I.e. it does not demonstrate the issue at hand. I'll update this issue if I catch the problem live.

**Comment by akhomyakov** [comment]
I just ran into the "misordered" edge nodes problem. You can see that I requested for those to be clustered in "b44f" first, and "3565" second. However, after clustering the response shows them in the opposite order. 
Since in the data resource in terraform there is no way to identify the VMs other than by index, there is no way for me to reliably reference them by resources such as gateway interfaces which require me to specify which edge VM to place it on.
```
↳ Create Edge Cluster
  POST https://labnsx101.lab.athenahealth.com/api/v1/edge-clusters
  201 Created ★ 8.3s time ★ 802B↑ 1.57kB↓ size ★ 11↑ 17↓ headers ★ 0 cookies
  ┌ ↑ raw ★ 350B
  │ {
  │     "description": "Load Balanacing Edge Cluster 1",
  │     "members": [
  │         {
  │             "transport_node_id": "ea86ad89-e1bf-4d63-a428-9468d5cdb44f"
  │         },
  │         {
  │             "transport_node_id": "bab5cc4c-0682-493f-8597-cde9b24b3565"
  │         }
  │     ],
  │     "resource_type": "EdgeCluster",
  │     "display_name": "LAB-PROD-EDGE-CLUSTER-LB-1"
  │ }
  └
  ┌ ↓ application/json ★ text ★ json ★ utf8 ★ 954B
  │ {
  │   "deployment_type" : "VIRTUAL_MACHINE",
  │   "members" : [ {
  │     "member_index" : 0,
  │     "transport_node_id" : "bab5cc4c-0682-493f-8597-cde9b24b3565"
  │   }, {
  │     "member_index" : 1,
  │     "transport_node_id" : "ea86ad89-e1bf-4d63-a428-9468d5cdb44f"
  │   } ],
  │   "cluster_profile_bindings" : [ {
  │     "resource_type" : "EdgeHighAvailabilityProfile",
  │     "profile_id" : "91bcaa06-47a1-11e4-8316-17ffc770799b"
  │   } ],
  │   "member_node_type" : "EDGE_NODE",
  │   "allocation_rules" : [ ],
  │   "enable_inter_site_forwarding" : false,
  │   "resource_type" : "EdgeCluster",
  │   "id" : "5d3971e6-27a2-4fb2-9cf1-bd12552da24a",
  │   "display_name" : "LAB-PROD-EDGE-CLUSTER-LB-1",
  │   "description" : "Load Balanacing Edge Cluster 1",
```

**Comment by tenthirtyam** [comment]
Bump.

**Comment by akhomyakov** [comment]
+1
Would still love this to exist. Just the other day we had to rebuild an
edge node by hand. Using APIs is not reasonable for a general operator. In
order to create rudimentary automation for edge cluster creation (of two) I
had to do query nsx controller and vcenter through at least 10
different HTTP GETs just to collect all the needed info that is then sent
with the HTTP POST to the NSX controller. And that's just to build from
nothing. Rebuilding is a separate set of calls.

--Andrey

**Comment by annakhm** [comment]
Fabric support is on the roadmap. Unfortunately it always get pushed due to more urgent asks, but we still plan to add it ;)

**Comment by annakhm** [comment]
Fabric support was finally added! We plan to release it as `Beta` in near future. Hence closing this
