### ISSUE TITLE
Failed to create VRF - Preferred edge path should be same as default tier-0

### ISSUE THREAD

**Issue by fgrehl** [vmware/terraform-provider-nsxt#674]
I use NSX-T 3.1 with Tier-0 and VRF. Tier-0 is configured as Active/Standby Preemptive and I need to set a preferred edge node to comply with my BGP peers.
Provider:  vmware/nsxt/Version 3.2.4

I already have a Tier-0 (Not created with TF) configured in A/S Preemptive with a preferred edge and want to create a VRF:

```
resource "nsxt_policy_tier0_gateway" "vrf" {
  display_name        = "VRF-Blue"
  ha_mode             = "ACTIVE_STANDBY"
  edge_cluster_path   = data.nsxt_policy_edge_cluster.ec.path
  failover_mode       = "PREEMPTIVE"

  vrf_config {
    gateway_path        = nsxt_policy_tier0_gateway.t0.path
  }
}
```

Creation fails:

```
nsxt_policy_tier0_gateway.vrf: Creating...
│ Error:  Failed to create Tier0 [ID]: Error during creating objects of type:LocaleServices (code 500157)
│ Related errors:
│ Preferred edge path should be same as default tier-0 /infra/tier-0s/[ID]. (code 528032)
│
│   with nsxt_policy_tier0_gateway.vrf,
│   on main.tf line 67, in resource "nsxt_policy_tier0_gateway" "vrf":
│   67: resource "nsxt_policy_tier0_gateway" "vrf" {
│
```

https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_tier0_gateway#preferred_edge_paths
According to the Provider documentation, preferred_edge_path can only be used with NSX Global Manager. In NSX-T you can set it without local manager.

Setting preferred_edge_path (Without using Global Manager) fails:

`Error: locale_service setting is only supported with NSX Global Manager`

Request: Option to set **preferred_edge_path** when creating **nsxt_policy_tier0_gateway** resources (Tier-0 or VRF) without a Global Manager.

**Comment by annakhm** [comment]
Hello @fgrehl and sorry for delay in response. Indeed today `locale_service` clause, which specifies `preferred_edge_path`, is only supported for Global Manager, however we do plan to support it for Local Manager as well. This enhancement will solve the issue.

**Comment by FabienMTP** [comment]
Hello @annakhm, do you have a release date for this enhancement (locale_service support for Local Manager) ? The lack of support for preferred edge node prevent us for using Terraform until now.

@fgrehl did you found a workaround ?

**Comment by fgrehl** [comment]
@FabienMTP Currently, I'm creating them manually and importing them into TF. The nsxt provider does know now about the preferred edge parameter so it does not try to change it. In general, I'm not so happy with VRF+Preffered Edges because you can not change them later.

1. Define Tier0/VRF in TF without preferred edge config
2. Create Tier0/VRF in NSX-T UI with Preferred Edge Config (No further Config)
3. Import Tier0/VRF `terraform import 'nsxt_policy_tier0_gateway.t0' display_name` 
4. Verify with `terraform plan` that it gets "updated in-place"

**Comment by annakhm** [comment]
Sorry for delay in response. The main issue that complicates exposing locale_service for local manager is import. When importing gateway, we have no indication whether the user wishes to use `locale_service` or `edge_cluster_path` in configuration. We are reluctant to add some kind of indication for this purpose in `id` field of the import command. We are considering adding this support anyway documenting this limitation for now. Your feedback here is appreciated - is `import` functionality something you would need?
