### ISSUE TITLE
[Feature] Support for Address Binding of nsxt_policy_segment

### ISSUE THREAD

**Issue by scila1996** [vmware/terraform-provider-nsxt#675]
Please add support for Address Binding in Policy Mode. I have a segment and have some VM to need to bind with several VM, for security. in NSX-T segment have 2 optional.

- Address Binding: Address bindings specify the IP and MAC address of a logical port and are used to specify the port allow-list in SpoofGuard.

- DHCP Set Static Bindings: Bind a static IP address to the MAC address of each VM (DHCP client). The static IP address must not overlap with the DHCP IP ranges and the DHCP Server IP addresses.

Many  thanks !

**Comment by annakhm** [comment]
Hi @scila1996, sorry for delay in response. Address bindings setting for segment is deprecated in NSX, address bindings for ports are used instead. If this relevant for your use case?

**Comment by scila1996** [comment]
> Hi @scila1996, sorry for delay in response. Address bindings setting for segment is deprecated in NSX, address bindings for ports are used instead. If this relevant for your use case?

Currently, I'm not needed to use this feature, thanks for your reply 😄
