### ISSUE TITLE
Resource Questions

### ISSUE THREAD

**Issue by rmtilson** [vmware/terraform-provider-nsxt#680]
Not sure if I am missing something but the nsxt_policy_vm_tags resource appears to only take a single VM ID, if that is the case does it make since to support multiple VM ID's? 

Also, when importing a group with nsxt_policy_group it appears that ExternalIDExpression is not supported. Is this something that could be?

**Comment by annakhm** [comment]
Hello @rmtilson, indeed this resource handles one vm only (the plural in resource name refers to tags, not vms). Is your use case to apply same tag set on multiple vms?
