### ISSUE TITLE
Create NSX policy group with variable

### ISSUE THREAD

**Issue by thenoob999** [vmware/terraform-provider-nsxt#682]
Hello,

I try to execute : 
terraform apply -var mygroup="SecurityGroupSNS"

I have the following error: 

│ Error: Invalid resource name
│
│   on main.tf line 40, in resource "nsxt_policy_group" "${ ... }":
│   40: resource "nsxt_policy_group" "${var.mygroup}" {
│
│ A name must start with a letter or underscore and may contain only letters, digits, underscores, and dashes.

I use this syntax: 
resource "nsxt_policy_group" "${var.mygroup}" {
  display_name = "${var.mygroup}"
  description  = "Terraform provisioned Group"
  criteria {
    condition {
      key         = "Tag"
      member_type = "VirtualMachine"
      operator    = "EQUALS"
      value       = "SecurityGroup|${varmygroup}"
    }
  }
}

In the documentation the example is : 
resource "nsxt_policy_group"  "group1" {

But is it not possible to use this because when I execute with a nex parameter for mygroup, terraform try to modify the "group1" while the name is not the same, the ports are not the same etc..

On others providers you have for example a "name" parameter which permit for a group to be unique and be used in "variable"

Thanks for your help
Best Regards

**Comment by annakhm** [comment]
Hello, the provider has no say in resource definition syntax - this is part of terraform core. I'm not aware of syntax that allows to use variable as resource name. I'm also not sure I understand your use case - could you please clarify why changing of terraform resource name is required?
