### ISSUE TITLE
Missing option to specify nsxt_policy_group membership via list of external IDs

### ISSUE THREAD

**Issue by CNakai** [vmware/terraform-provider-nsxt#683]
It seems there is some missing parity between the nsxt policy API which allows for ExternalIDExpressions in specifying nsxt_policy_group membership and the Terraform provider which does not seem to support this option.

Is this intentional or is this feature at all planned for a future version of the provider?

**Comment by annakhm** [comment]
Hello, yes, we're aware that group definitions evolved on NSX, and a few of those are not covered provider. I'm marking this as enhancement and keep this issue open to help with prioritization.

**Comment by CNakai** [comment]
Awesome, thank you.  This feature is really important for the work my team is doing (#imsureeveryonesaysthat) because it seems to be the only way to get a group that has more than 5 members that aren't tied together by common tags since there is a limit of 5 criteria for groups that use those.

**Comment by tonygumbrell** [comment]
I also have this issue and it's causing me major lifecycle issues. VMs are assigned to a terraform created security group via vRA as VIF members. Once a VIF member is present in the security group if I re-runn an apply I get 'Unsupported criteria type: ExternalIDExpression'. This essentially renders this provider unusable at present.

**Comment by CNakai** [comment]
Hey @annakhm, any update on where this might be on the provider's roadmap?

**Comment by annakhm** [comment]
Hi @CNakai, this feature is prioritized, and we'll likely be included in coming release (mid-April)

**Comment by alagoutte** [comment]
> Excellent, thanks for the update @annakhm. Did it end up making it into the mid-April release?
> 
> Update: In an effort to not be a total lazy-bones, I took a look at the ol' CHANGELOG.md file and did not see it. I assume this has been moved to the next release. Is your release schedule monthly, quarterly, or something else entirely? :)

i think, it is better to look Github Release https://github.com/vmware/terraform-provider-nsxt/releases

**Comment by CNakai** [comment]
Ah, thanks @alagoutte!  I ctrl+f'd for "policy" and "group" and the results in the latest release didn't seem connected to this enhancement.  Am I blind or just looking for the wrong things?  Or were you just suggesting that the releases are a better place to look in general?

**Comment by annakhm** [comment]
This was added with https://github.com/vmware/terraform-provider-nsxt/pull/733, and next release will be hopefully out tomorrow. Sorry for the delay and thanks for your patience!
