### ISSUE TITLE
Add support for response_header_size in resource nsxt_lb_http_application_profile

### ISSUE THREAD

**Issue by thefluffysysop** [vmware/terraform-provider-nsxt#690]
We have a customer that needs to set a specific change to NSX-T Load Balancer (in API 'manager' mode) , this is a setting not exposed in the UI, but is in the API.

It is a property 'response_header_size' of '/api/v1/loadbalancer/application-profiles'  (terraform: nsxt_lb_http_application_profile)
Unfortunately this property cannot currently be set in the (manager mode) provider ( https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/lb_http_application_profile )

We would like this to be added to
https://github.com/vmware/terraform-provider-nsxt/blob/master/nsxt/resource_nsxt_lb_http_application_profile.go

(maybe also add 'response_buffering' while at it? ;) 

The original reference for us when troubleshooting:
https://community.pivotal.io/s/article/OIDC-Response-Header-overflow?language=en_US

API Reference: https://vdc-download.vmware.com/vmwb-repository/dcr-public/d6de7a5e-636f-4677-8dbd-6f4ba[…]i_includes/method_ReadLoadBalancerApplicationProfile.html

**Comment by thefluffysysop** [comment]
I was advised by @tenthirtyam to tag @annakhm  (maintainer) @tvigneron  (PM) on the issue ;)

**Comment by martinrohrbach** [comment]
@annakhm 
I was just looking into this as my client needs this as well and it looked like an easy fix. However, the code depends on https://github.com/vmware/go-vmware-nsxt/blob/master/loadbalancer/lb_http_profile.go and the "response_header_size" parameter from the API hasn't made it there (yet?).

Is there a preferred (and elegant) way to work around that (maybe you had the same problem in another resource I'm not aware of)?

**Comment by annakhm** [comment]
Hi @martinrohrbach, if this resource was added on policy side (with full set of parameters), would this solve the problem for you?

**Comment by martinrohrbach** [comment]
@annakhm Unfortunately this would not help us in the short term as we are unable to migrate the affected load balancers to policy API at the moment (legacy integrations using the manager API). For now, we've manually modified the application profiles using the API directly (as the NSX GUI also does not expose the response_header_size parameter) but now our IaC does not quite represent our production anymore. 

Having said that, a resource to create application profiles in policy would definitely help us as well and I could trigger another reevaluation to move some more ressources over to policy (albeit probably not the one affected here).

So you also don't see an easy solution to get this implemented?

**Comment by annakhm** [comment]
Hi @martinrohrbach, unfortunately non-policy resources are not prioritized since these are deprecated on NSX. We are evaluating migration options from MP po Policy.
