### ISSUE TITLE
nsxt_policy_context_profile does not support user created FQDN domain_name values

### ISSUE THREAD

**Issue by tullydwyer** [vmware/terraform-provider-nsxt#698]
### Describe the bug

Hi there,

We are trying to use nsxt_policy_context_profile to create Context Profiles containing 'user' created FQDN's for example `bob.bob.com` . 

When we try to use 'user' created FQDN's we get the following error:
`Error: Attribute values [bob.bob.com] are not valid for attribute type domain_name`

We are able to use the 'user' created FQDN's via the web console.

### Reproduce steps:
1. Create the user FQDN in the web console.
![image](https://user-images.githubusercontent.com/7508115/146312917-54d6e0f8-131c-4c3c-8d4a-0188478ae2de.png)
2. Try to create a Context Profile referencing the user FQDN.
Terraform:
```terraform
resource "nsxt_policy_context_profile" "fails" {
  display_name = "fails"
  description  = "fails"
  domain_name {
    value       = [
      "bob.bob.com"
    ]
  }
}
```
3. Error:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # nsxt_policy_context_profile.fails will be created
  + resource "nsxt_policy_context_profile" "fails" {
      + description  = "fails"
      + display_name = "fails"
      + id           = (known after apply)
      + nsx_id       = (known after apply)
      + path         = (known after apply)
      + revision     = (known after apply)

      + domain_name {
          + value = [
              + "bob.bob.com",
            ]
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
nsxt_policy_context_profile.fails: Creating...
╷
│ Error: Attribute values [bob.bob.com] are not valid for attribute type domain_name
│
│   with nsxt_policy_context_profile.fails,
│   on main.tf line 18, in resource "nsxt_policy_context_profile" "fails":
│   18: resource "nsxt_policy_context_profile" "fails" {
│
╵
```

### Expected behaviour
Create the Context Profile same as the web console:
![image](https://user-images.githubusercontent.com/7508115/146313561-c4015deb-4a20-4041-8c3d-ad180a1858c7.png)

Thanks,
Tully

### Additional context

nsxt = {
  source = "vmware/nsxt"
  version = "3.2.5"
}

**Comment by jorgemarti** [comment]
Would be really appreciated.

**Comment by tullydwyer** [comment]
Hi there @annakhm, I would consider this a bug as the provider does not behave the same as the NSX-T web console?

**Comment by tenthirtyam** [comment]
I would view this as a `bug` as well. 

Based on the issue report, I would expect the acceptance test cases that use `testAccNsxtPolicyContextProfileAttributeDomainNameTemplate` to fail.

https://github.com/vmware/terraform-provider-nsxt/blob/866e72278ce144c181fb6750c6ce976f5f3effda/nsxt/resource_nsxt_policy_context_profile_test.go#L317-L322

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tullydwyer** [comment]
`*-myfiles.sharepoint.com` is a 'System' created FQDN which does work with the `nsxt_policy_context_profile` resource

![image](https://user-images.githubusercontent.com/7508115/185827205-3ab9de74-3e03-4268-9660-d988ef3fb373.png)
