### ISSUE TITLE
nsxt_policy_service to group services

### ISSUE THREAD

**Issue by akhomyakov** [vmware/terraform-provider-nsxt#700]
### Is your feature request related to a problem? Please describe.

![Screen Shot 2021-12-16 at 8 59 34 AM](https://user-images.githubusercontent.com/16153883/146416126-e880ad1a-5b8c-49e2-b7f7-a4af042f9713.png)
It is not clear to me from documentation how one can create a service group made up from already existing services. In other words, how do I declare the above in TF?
Documentation for nsxt_policy_service only shows how to declare a new service, but not a collection of already declared services.

### Describe the solution you'd like

Ability to group services so the new service group can be used in the rules rather than individually listing every service in the policy rule.

### Describe alternatives you've considered

I can't imagine what to do other than to group them in the UI by hand.

**Comment by akhomyakov** [comment]
I created a service group in the UI by hand
![Screen Shot 2022-01-24 at 11 22 34 AM](https://user-images.githubusercontent.com/16153883/150850035-dec6bb0c-70f0-44b7-adc3-c989a3066cb6.png)

I then declared a tf resource
```
resource "nsxt_policy_service" "INFRA-SVC-LNX" {
  display_name = "INFRA-SVC-LNX"

}
```

And ran a 
```
$> terraform import module.firewall-policy-objects.nsxt_policy_service.INFRA-SVC-LNX INFRA-SVC-LNX
module.firewall-policy-objects.nsxt_policy_service.INFRA-SVC-LNX: Importing from ID "INFRA-SVC-LNX"...
module.firewall-policy-objects.nsxt_policy_service.INFRA-SVC-LNX: Import prepared!
  Prepared nsxt_policy_service for import
module.firewall-policy-objects.nsxt_policy_service.INFRA-SVC-LNX: Refreshing state... [id=INFRA-SVC-LNX]
╷
│ Error: Unrecognized Service Entry Type NestedServiceServiceEntry
│
│
╵

Releasing state lock. This may take a few moments...
```

Best on the error message, I conclude that this is simply not supported by the current version of the nsxt_policy_service resource


Would you, please, please, please, add this functionality to the nsxt_policy_service resource!?

**Comment by yasvanth** [comment]
Hi Team, any update on this feature to add nested services?

**Comment by AxFrancois** [comment]
Hi everyone. I also need to use this feature. Any news on it ?

**Comment by ChevyNovaLN** [comment]
Just ran into this issue as well.   Is there anyone looking to add nested services to the NSXT provider or did this die?
