### ISSUE TITLE
Documentation error for nsxt_policy_gateway_route_map

### ISSUE THREAD

**Issue by akhomyakov** [vmware/terraform-provider-nsxt#704]
### Describe the bug

Documentation at https://github.com/vmware/terraform-provider-nsxt/blob/ef8c8cbde1106b74dbbcbdcb3c35ce92ab570633/website/docs/r/policy_gateway_route_map.html.markdown?plain=1#L59 provides invalid options for the match_operator as evidenced by the error message copied below as well as the source code for the tests found [here](https://github.com/vmware/terraform-provider-nsxt/blob/ef8c8cbde1106b74dbbcbdcb3c35ce92ab570633/nsxt/resource_nsxt_policy_gateway_route_map_test.go#L172)
```
2021-12-28 10:40:57|username@hostname:~/git/nsxt-terraform/environments/LAB (production)
$> terraform plan
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...
╷
│ Error: expected entry.0.community_list_match.0.match_operator to be one of [MATCH_ANY MATCH_ALL MATCH_EXACT MATCH_COMMUNITY_REGEX MATCH_LARGE_COMMUNITY_REGEX], got COMMUNITY_REGEX
│
│   with nsxt_policy_gateway_route_map.LB-IN-FROM-DEV-PROD-LB-T0-RTR1,
│   on PROD-LB-T0-RTR1-route-map.tf line 8, in resource "nsxt_policy_gateway_route_map" "LB-IN-FROM-DEV-PROD-LB-T0-RTR1":
│    8:             match_operator = "COMMUNITY_REGEX"
│
╵
```

### Reproduction steps

```bash
1. Set match_operator to one of the documented values
2. Run `terraform plan`
3. Observe the issue in the error message output
```

### Expected behavior

I'd like the documentation to match reality.

**Comment by alagoutte** [comment]
Hi,

yes, confirmed => https://vdc-download.vmware.com/vmwb-repository/dcr-public/ce4128ae-8334-4f91-871b-ecce254cf69e/488f1280-204c-441d-8520-8279ac33d54b/api_includes/types_CommunityMatchCriteria.html

do you plan to push a fix ?

**Comment by annakhm** [comment]
Thanks for reporting this. Of course we'll be fixing this.
