### ISSUE TITLE
nsxt_policy_segment - advanced config - address_pool_path seems to be incorrect

### ISSUE THREAD

**Issue by burnsjared0415** [vmware/terraform-provider-nsxt#707]
### Describe the bug

When running resource "nsxt_policy_segment" and trying to add ip pool to segment, pool never gets added. Ran Postmon for the value and key and realized it is not address_pool_path in NSX-T 3.2.1, it seems to be address_pool_paths instead. Need to get this updated.

### Reproduction steps

```bash
1.Try and create a segment with IP Pool assignment
2.Run API call policy/api/v1/infra/segments/ to see that the key is different
3.
...
```

### Expected behavior

Add the IP pool to the Segment

**Comment by annakhm** [comment]
Hello @burnsjared0415, the provider supports single pool path as of now (while the platform supports multiple pools for different IP versions). Single pool is supposed to work. Could you please provide your configuration and logs, to show the problem in detail. Thank you!

**Comment by burnsjared0415** [comment]
## Create Segments with Static Address with IP Pool required configured
resource "nsxt_policy_segment" "segment_static_with_ip_pool" {
  display_name = var.segment_static_name_with_pool
  connectivity_path = data.nsxt_policy_tier1_gateway.tier1_gateway.path
  transport_zone_path = data.nsxt_policy_transport_zone.overlay_tz.path
  subnet {
    cidr = var.segment_static_name_with_pool_cidr
    }
  advanced_config {
   address_pool_path = data.nsxt_policy_ip_pool.ip_pool.path
  }
}

if you look at the segment info here is what NSX-T wants:
"advanced_config": {
                "address_pool_paths": [
                    "/infra/ip-pools/d7f4aaa5-18c9-440d-a5ec-9ac935adc925"
                ],

**Comment by alagoutte** [comment]
it is not only a typo and missing a s on https://github.com/vmware/terraform-provider-nsxt/blob/529889ac80c6b139369360167729e38eba06eeb2/nsxt/segment_common.go#L161

**Comment by burnsjared0415** [comment]
So do i need to change my statements or is this a bug?

**Comment by alagoutte** [comment]
for me, it is a bug...

**Comment by annakhm** [comment]
Thank you for the details, confirmed its a bug. Fix coming soon.

**Comment by annakhm** [comment]
Just to be clear - we still support only one IP pool.

**Comment by burnsjared0415** [comment]
Just need one because that is a nsx-t restriction

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
