### ISSUE TITLE
nsxt_policy_vm errors when returning multiple results 

### ISSUE THREAD

**Issue by kalenarndt** [vmware/terraform-provider-nsxt#710]
### Describe the bug

The `nsxt_policy_vm` data resource shows that all of the arguments are optional based on the provider documentation located [here](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/data-sources/policy_vm#argument-reference). 

If you don't supply any arguments it will return all VMs in inventory but instead of just storing the objects in state the data source returns an error with the amount of objects that are found and stops the run. 

Example Error:

```╷
│ Error: Found 33 Virtual Machines with name prefix: 
│ 
│   with data.nsxt_policy_vm.check,
│   on main.tf line 34, in data "nsxt_policy_vm" "check":
│   34: data "nsxt_policy_vm" "check" {
│ 
╵
```

### Reproduction steps

```bash
1. Create a data block like the following:

 "nsxt_policy_vm" "check" {
}
2. Do a Terraform plan
```

### Expected behavior

The objects should be stored under the data block so they could be referenced or iterated over if users are looking for VMs potentially with a specific naming convention. 

Alternatively the resource should support prefix filtering or name filtering similar to how security group membership works. That way users can retrieve a subset of VMs or All VMs or only a specific VM based on the need. 

If this is not the intended use or direction I would suggest the documentation state that one of the arguments is required when utilizing the resource.

**Comment by annakhm** [comment]
Hi @kalenarndt, traditionally data source without plural in the name returns a single object in this provider. I understand the need to retrieve multiple objects, so we need to make a consistent decision here - one option is to add `nsxt_policy_vms` data source and another to add `items` attribute to same data source. If would be great to hear feedback from users on what they prefer, as this will affect other data sources as well.

**Comment by kalenarndt** [comment]
@annakhm I would say that adding an additional datasource would solve the challenge but it could potentially confuse the end user.  An items reference should work and reduce the amount of additional data sources that need to be maintained. 

The provider docs say `The Display Name prefix of the Virtual Machine to retrieve` under display_name. A prefix to me when I was doing NSX-T was something where I could look for a naming pattern and get multiple results.

**Comment by annakhm** [comment]
Hi @kalenarndt, thank you for the feedback!
For now `nsxt_policy_vms` data source was added. We're reluctant to change the behavior of prefix match right now, since this behavior is shared in almost all data sources, but its a viable idea for the future.
