### ISSUE TITLE
Lazy loading the provided

### ISSUE THREAD

**Issue by benohara** [vmware/terraform-provider-nsxt#711]
### Describe the bug

Currently the provider doesnt lazy load.

This means it not possible to deploy a new NSXT Manager as a vsphere.virtual_machine resource and then connect to the newly deployed VCSA to configure it with this provider.

This requires splitting into multiple workspaces which doubles licensing costs.

Please implement lazy loading in this provider.

### Reproduction steps

```bash
1.
2.
3.
...
```

### Expected behavior

Able to run terraform with a provider configured to talk to a as yet non existent NSXT manager and only connect once the resources are required to be created.

**Comment by annakhm** [comment]
We plan to implement this with NSX fabric support

**Comment by annakhm** [comment]
Done with https://github.com/vmware/terraform-provider-nsxt/pull/948 - `on_demand_connection` provider attribute controls this setting
