### ISSUE TITLE
nsxt_policy_tier1_gateway edge_cluster_path bug

### ISSUE THREAD

**Issue by Naumancc** [vmware/terraform-provider-nsxt#716]
### Describe the bug

Resource = nsxt_policy_tier1_gateway
Argument = edge_cluster_path

Terraform does not remove an edge cluster from a T1 using the edge_cluster_path argument once it's been created.  When deleted from the code and issuing a 'terraform plan' terraform does not recognise the deletion and the deletion can't be made. 

Changing the edge cluster to another works fine, the problem is specific to removal.

### Reproduction steps

```bash
1. Create a Tier 1 gateway using nsxt_policy_tier1_gateway
2. add a edge_cluster_path to the tier 1 gateway
3. remove the edge_cluster_path from the tier 1 gateway by deleting the line in tf
4. terraform will not see the change in the code when 'terraform plan' or 'terraform apply' is executed
...
```

### Expected behavior

The edge_cluster_path should be removed from the Tier 1 Gateway. 

### Additional context

Maybe related to the hierarchical API (edge cluster is added using a child policy) and a GET request not returning the an edge cluster.

**Comment by annakhm** [comment]
Hi @Naumancc, sorry for delay in response. We are aware of this issue, and this is going to be solved by supporting the `locale_service` clause on gateways (it is currently supported for Global Manager only).
