### ISSUE TITLE
VMC / Compute Gateway / Groups - User is not authorized to perform this operation on the application. Please contact the system administrator to get access

### ISSUE THREAD

**Issue by sebastiangrugel** [vmware/terraform-provider-nsxt#729]
### Describe the bug

To create FW rules on VMC Compute Gateway, we should before has created groups for source and destination field.
I decided to created them from code before rule configuration but receive error:

`
│ Error:  Failed to create Group cc93141c-23e6-4081-996c-68e25f2a206f: User is not authorized to perform this operation on the application. Please contact the system administrator to get access. (code 401)
│
│   with nsxt_policy_group.group1,
│   on vmc_issue_nsxt-dfw1.tf line 12, in resource "nsxt_policy_group" "group1":
│   12: resource "nsxt_policy_group" "group1" {
│
`
![image](https://user-images.githubusercontent.com/19813648/159475120-e5978fb1-deb3-4779-904e-015008d8889c.png)

Code which i used:

`
resource "nsxt_policy_group" "group1" {
  display_name = "tf-group1"
  description  = "Terraform provisioned Group"
  dom
}
`

### Reproduction steps

```bash
1. Deploy code by command "terraform apply -auto-approve"
2. Described above issue...
```

### Expected behavior

New group should be created in VMC Console.

Example of other groups:
![image](https://user-images.githubusercontent.com/19813648/159475317-1df83a51-4244-48d0-b684-d3d117a97a05.png)

**Comment by annakhm** [comment]
Hi @sebastiangrugel, on VMC you should specify VMC-specific domain (f.e. `cgw`):

`resource "nsxt_policy_group" "group1" { 
  display_name  = "tf-group1"
  description      = "Terraform provisioned Group"
  domain            = "cgw"
}`

Hope this helps

**Comment by annakhm** [comment]
Closing this - please reopen if issue still exists
