### ISSUE TITLE
Rules / Object modification ordering not correct

### ISSUE THREAD

**Issue by frederic-urban** [vmware/terraform-provider-nsxt#739]
### Describe the bug

Hello,

When modifing an object in a rules, (ie replace an object by another) if the formerly used nsx_policy_group is destroyed in the same run, terraform tries to destroy the group before updating the nsxt_policy_security_policy resource.

### Reproduction steps

```bash
1. Create a group ressource and security policy with a rule using it
2. Apply using the terraform provider
3. Modify the terraform code replacing groups using another name + id and correct the security policy using the new group
4. Apply and you should see that resource group destruction will be done before policy is updated. This will cause NSX-T to complain about the fact that the group is in use in the policy
...
```

### Expected behavior

Create all ressource of the plan first
Update all ressources of the plan in second
Destroy all required ressources of the plan a the end

### Additional context

Here is a run with a workaround using target switch to avoid such a situation:
#######

Context, plan is to change nsxt_policy_group.Yet_Another_Random_Group_ID in the nsxt_policy_security_policy.A_SUPER_POLICY by nsxt_policy_group.Yet_Another_Random_Group_ID as source:

#######

[urbanfe2@ladms0u1 py-tool-coin2table> terraform -chdir=/appli/VNOM/terraform/security/w02/ plan
nsxt_policy_group.Another_Random_Group_ID: Refreshing state... [id=e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2]
nsxt_policy_group.A_Group_Which_wont_Move: Refreshing state... [id=c4245baa-7b68-4cbf-8c69-9b1c4b47b895]
nsxt_policy_service.TCP-3260: Refreshing state... [id=43666418-9f30-4fc2-b72f-3edafa9b3b6f]

... So much lines

nsxt_policy_security_policy.SUPER_POLICY: Refreshing state... [id=d6623c64-67ac-445c-9e8f-941f63d49f8e]
nsxt_policy_security_policy.SUPER_POLICY2: Refreshing state... [id=afa3c181-c500-4529-a800-5010ed334577]
nsxt_policy_predefined_gateway_policy.default-blaobaoblaoab: Refreshing state... [id=Policy_Default_Infra-tier1-18ace36b-002b-41de-bb66-bf2dd94bead0]
nsxt_policy_security_policy.SUPER_POLICY3: Refreshing state... [id=dee1c762-dd34-40e9-9d57-973244935f2c]
nsxt_policy_predefined_gateway_policy.yesablalblala: Refreshing state... [id=Policy_Default_Infra-tier1-933e1e9e-50c2-466f-9f4b-b3ed7c99f982]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
  - destroy

Terraform will perform the following actions:

  # nsxt_policy_group.Another_Random_Group_ID will be destroyed
  - resource "nsxt_policy_group" "Another_Random_Group_ID" {
      - description  = "Algosec import of the object Another_Random_Group_ID" -> null
      - display_name = "Another_Random_Group_ID" -> null
      - domain       = "default" -> null
      - id           = "e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2" -> null
      - nsx_id       = "e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2" -> null
      - path         = "/infra/domains/default/groups/e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2" -> null
      - revision     = 0 -> null

      - criteria {

          - ipaddress_expression {
              - ip_addresses = [
                  - ".../22",
                ] -> null
            }
        }
    }

  # nsxt_policy_group.Yet_Another_Random_Group_ID will be created
  + resource "nsxt_policy_group" "Yet_Another_Random_Group_ID" {
      + description  = "Import of the object Yet_Another_Random_Group_ID"
      + display_name = "Yet_Another_Random_Group_ID"
      + domain       = "default"
      + id           = (known after apply)
      + nsx_id       = (known after apply)
      + path         = (known after apply)
      + revision     = (known after apply)

      + criteria {

          + ipaddress_expression {
              + ip_addresses = [
                  + ".../22",
                  + ".../26",
                ]
            }
        }
    }

... Lot of modifications unrelated ...

  # nsxt_policy_security_policy.A_SUPER_POLICY will be updated in-place
  ~ resource "nsxt_policy_security_policy" "A_SUPER_POLICY" {
        id              = "1bb7458f-d613-4eea-a211-1e28f5eafab1"
        # (11 unchanged attributes hidden)

      ~ rule {
          ~ source_groups         = [
              - "/infra/domains/default/groups/e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2",
            ] -> (known after apply)
            # (17 unchanged attributes hidden)
        }
      + rule {
          + action                = "ALLOW"
          + destination_groups    = [
              + "/infra/domains/default/groups/8c4ecc87-6a44-4d35-8c85-90771b8a4e1b",
            ]
          + destinations_excluded = false
          + direction             = "IN_OUT"
          + disabled              = false
          + display_name          = "Cluster ...."
          + ip_version            = "IPV4_IPV6"
          + logged                = true
          + notes                 = "..."
          + services              = [
              + "/infra/services/44b933ea-67c6-4844-ad47-7a8b3e2a499b",
            ]
          + source_groups         = [
              + "/infra/domains/default/groups/7a1951bb-7a91-4e52-88f3-2748b5a54f45",
            ]
          + sources_excluded      = false
        }
    }

Plan: 5 to add, 12 to change, 1 to destroy.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

#######

Workaround to create and modify first using -target switch:

[urbanfe2@ladms0u1 py-tool-coin2table> terraform -chdir=/appli/VNOM/terraform/security/w02/ apply -target=nsxt_policy_group.Yet_Another_Random_Group_ID -target=nsxt_policy_security_policy.A_SUPER_POLICY

#######

nsxt_policy_group.Foooobarrrr: Refreshing state... [id=9127267f-3bda-4405-947b-396ff8b04922]
nsxt_policy_group.FoooobarrrrAgain: Refreshing state... [id=7a1951bb-7a91-4e52-88f3-2748b5a54f45]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # nsxt_policy_group.Yet_Another_Random_Group_ID will be created
  + resource "nsxt_policy_group" "Yet_Another_Random_Group_ID" {
      + description  = "Import of the object Yet_Another_Random_Group_ID"
      + display_name = "Yet_Another_Random_Group_ID"
      + domain       = "default"
      + id           = (known after apply)
      + nsx_id       = (known after apply)
      + path         = (known after apply)
      + revision     = (known after apply)

      + criteria {

          + ipaddress_expression {
              + ip_addresses = [
                  + ".../22",
                  + ".../26",
                ]
            }
        }
    }

  # nsxt_policy_security_policy.A_SUPER_POLICY will be updated in-place
  ~ resource "nsxt_policy_security_policy" "A_SUPER_POLICY" {
        id              = "1bb7458f-d613-4eea-a211-1e28f5eafab1"
        # (11 unchanged attributes hidden)

      ~ rule {
          ~ source_groups         = [
              + "/infra/domains/default/groups/6882b204-10a0-4cad-8f93-dcfcb5d8823d",
              - "/infra/domains/default/groups/e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2",
            ]
            # (17 unchanged attributes hidden)
        }
      + rule {
          + action                = "ALLOW"
          + destination_groups    = [
              + "/infra/domains/default/groups/8c4ecc87-6a44-4d35-8c85-90771b8a4e1b",
            ]
          + destinations_excluded = false
          + direction             = "IN_OUT"
          + disabled              = false
          + display_name          = "..............."
          + ip_version            = "IPV4_IPV6"
          + logged                = true
          + notes                 = "..."
          + services              = [
              + "/infra/services/44b933ea-67c6-4844-ad47-7a8b3e2a499b",
            ]
          + source_groups         = [
              + "/infra/domains/default/groups/7a1951bb-7a91-4e52-88f3-2748b5a54f45",
            ]
          + sources_excluded      = false
        }
    }

Plan: 1 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically
│ suggests to use it as part of an error message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

nsxt_policy_group.Yet_Another_Random_Group_ID: Creating...
nsxt_policy_security_policy.A_SUPER_POLICY: Modifying... [id=1bb7458f-d613-4eea-a211-1e28f5eafab1]
nsxt_policy_group.Yet_Another_Random_Group_ID: Creation complete after 1s [id=6882b204-10a0-4cad-8f93-dcfcb5d8823d]
nsxt_policy_security_policy.A_SUPER_POLICY: Modifications complete after 3s [id=1bb7458f-d613-4eea-a211-1e28f5eafab1]
╷
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully
│ updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when
│ Terraform specifically suggests to use it as part of an error message.
╵

Apply complete! Resources: 1 added, 1 changed, 0 destroyed.

#######

Here we finally apply the rest of actions since the dependancy is cleaned up

#######

[urbanfe2@ladms0u1 py-tool-coin2table> terraform -chdir=/appli/VNOM/terraform/security/w02/ apply
nsxt_policy_group.BlaBlaBLaaaaa: Refreshing state... [id=8b1a40db-3592-4a7a-bd73-1d162ba5bf30]
nsxt_policy_group.Another_Random_Group_ID: Refreshing state... [id=e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2]

... Lot of linnnnessss

nsxt_policy_predefined_gateway_policy.default-Blablalblalalaa: Refreshing state... [id=Policy_Default_Infra-tier1-18ace36b-002b-41de-bb66-bf2dd94bead0]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # nsxt_policy_group.Another_Random_Group_ID will be destroyed
  - resource "nsxt_policy_group" "Another_Random_Group_ID" {
      - description  = "Import of the object Another_Random_Group_ID" -> null
      - display_name = "Another_Random_Group_ID" -> null
      - domain       = "default" -> null
      - id           = "e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2" -> null
      - nsx_id       = "e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2" -> null
      - path         = "/infra/domains/default/groups/e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2" -> null
      - revision     = 0 -> null

      - criteria {

          - ipaddress_expression {
              - ip_addresses = [
                  - ".../22",
                ] -> null
            }
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

nsxt_policy_group.Another_Random_Group_ID: Destroying... [id=e1a6ac2e-cb8f-4eee-a6c7-c7c753793dd2]
nsxt_policy_group.Another_Random_Group_ID: Destruction complete after 2s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.

**Comment by annakhm** [comment]
Hi @frederic-urban, this sounds like a lifecycle issue:
https://github.com/vmware/terraform-provider-nsxt/blob/master/website/docs/guides/faq.html.markdown#dependency-errors-lifecycle

**Comment by annakhm** [comment]
Closing this as per above comment, please reopen if needed.
