### ISSUE TITLE
Add support for creating compute managers

### ISSUE THREAD

**Issue by LifeOfBrianOC** [vmware/terraform-provider-nsxt#748]
### Is your feature request related to a problem? Please describe.

Currently there is no support for creating compute managers in NSX-T. A compute manager, like vCenter, is used to manage host transport nodes & also to deploy additional appliance nodes in a cluster. To support adding host transport nodes from additional vCenters, additional compute managers may be required.

### Describe the solution you'd like

Please consider adding support for compute manager creation. This will enable end to end configuration of an NSX-T instance using Terraform without the need to use external tooling like ansible.

**Comment by annakhm** [comment]
Support was added
