### ISSUE TITLE
Add support for creating transport zones

### ISSUE THREAD

**Issue by LifeOfBrianOC** [vmware/terraform-provider-nsxt#749]
### Is your feature request related to a problem? Please describe.

Currently there is no support for creating transport zones in NSX-T. The provider assumes transport zones are pre-created and are only available as a datasource.

### Describe the solution you'd like

Please consider adding support for creating transport zones as resources to enable users to add additional transport zones, either overlay or vlan backed.

**Comment by sachinsprasad** [comment]
I am also interested in this feature.
