### ISSUE TITLE
Add support for External IPAM in Network Profiles -> Network Policies

### ISSUE THREAD

**Issue by bmarkussen** [vmware/terraform-provider-nsxt#750]
### Is your feature request related to a problem? Please describe.

When creating Network Policies in Network Profiles is not possible to point to an external IPAM (Infoblox) and add an IP Block.

I'm using the Infoblox IPAM 1.4  Integration in vRA. 

### Describe the solution you'd like

I think we need:
- A "externalIpBlockIds" argument in the Resource: vra_network_profile 
- A Datasource to lookup the externalIpBlockIds
- A Datasource to lookup the isolationNetworkDomainId - I expect that Data Source: vra_network_domain will work.

In vRA API it is possible:

Get the externalIpBlockIds:
  {{host}}/iaas/api/external-ip-blocks?%24filter=name+eq+'10.0.0.0/20'

Get the isolationNetworkDomainId:
  {{host}}/iaas/api/network-domains?apiVersion=2021-07-15&$filter=name+eq+'transportzonename'

Create the Network Profile:
  {{host}}/iaas/api/network-profiles?apiVersion=2021-07-15

{
  "description": "Testing Network Profile",
  "isolationNetworkDomainId": "7e9bdb67-87fa-4e19-8121-e77a3d401ec7",
  "externalIpBlockIds": [
    "d62ad6f4-9710-4ec5-978b-957fecaa3911"
  ],
  "customProperties": {
    "datacenterId": "Datacenter:datacenter-3",
    "onDemandNetworkIPAssignmentType": "static"
  },
  "regionId": "57a18357-3268-4f46-9b26-4629ed9a25b0",
  "name": "Testing Network Profile",
  "isolationExternalFabricNetworkId": null,
  "isolationType": "SUBNET",
  "isolatedNetworkCIDRPrefix": 28
}

**Comment by tvigneron** [comment]
The Network Profile and its Network Policy is a vRA construct.
A datasource for vRA like vra_network_domain would need to be in another provider (the vRA one)
What is the expectation on the NSX-T Terraform Provider?

**Comment by bmarkussen** [comment]
Hi tvigneron,

You are absolutely right. I have posted this the wrong place. 

Please close this issue. 

/Brian
