### ISSUE TITLE
Add resource to manage the Distributed Firewall settings "Exclusion list"

### ISSUE THREAD

**Issue by harishkalyanpur** [vmware/terraform-provider-nsxt#757]
### Is your feature request related to a problem? Please describe.

We cannot update distributed firewall exclusion list with terraform at the moment. This requires us to manually update.

### Describe the solution you'd like

New resource to manage the Distributed Firewall Settings "Exclusion List".

### Describe alternatives you've considered

Manually updating the exclusion list.

https://docs.vmware.com/en/VMware-Cloud-on-AWS/services/com.vmware.vmc-aws-networking-security/GUID-F6012765-7969-4ACC-92E0-CE716AAF92CE.html 

We are not sure If there is an internal API call available for the same.

**Comment by Girdhar1982** [comment]
any update on this request.. is this functionality available?

**Comment by vitality411** [comment]
I am also interested in this feature.
