### ISSUE TITLE
Field sequence_number in rule for nsxt_policy_security_policy is not applied

### ISSUE THREAD

**Issue by ykondratov** [vmware/terraform-provider-nsxt#763]
### Describe the bug

Field `sequence_number` for rules in `nsxt_policy_security_policy` resource is not applied.

Example: in policy below I specify sequence_numbers as 10 and 20, `terraform apply` is successful. But when I run `terraform plan` after that - sequence_numbers are shown as 0 and 1.

Also if I curl `GET /policy/api/v1/infra/domains/default/security-policies/test_access_id` I see sequence_numbers 0 and 1 for rules.

```
resource "nsxt_policy_security_policy" "test_access" {
  display_name = "test_access"
  sequence_number = 10
  description  = "Test security policy"
  category     = "Infrastructure"
  locked       = false
  stateful     = true
  tcp_strict   = true

  rule {
    sequence_number = 10
    display_name = "permit icmp"
    description = "permit icmp"
    action = "ALLOW"
    source_groups = []
    destination_groups = []
    services = []
  }

  rule {
    sequence_number = 20
    display_name = "permit ssh"
    description = "permit ssh"
    action = "ALLOW"
    source_groups = []
    destination_groups = []
    services = []
  }
}
```

### Reproduction steps

```bash
1. Create security policy with 2 rules and specify sequence_number for each rule
2. Execute terraform apply
3. Execute terraform plan - terraform will see the change in state, meaning that sequence_numbers do not match the resource
```

### Expected behavior

Expected behaviour is that after `terraform apply` values of `sequence_number` specified in resource are correctly applied to actual rules in NSX-T

### Additional context

TF provider versions: 3.4, 3.7 
NSX-T version 3.1.2.1.0.17975795

**Comment by annakhm** [comment]
Hi @ykondratov, sorry for delay in response. I can't reproduce the issue you describe with provider version 3.3.1, sequence numbers are applied correctly for me. However I'm submitting a [related change](https://github.com/vmware/terraform-provider-nsxt/pull/931), that would verify sequence numbers the user specifies are consistent with rule order.
It would be appreciated if you could let us know if you're still experiencing this issue with latest provider version.

**Comment by annakhm** [comment]
This should be addressed with latest provider version. Please reopen if needed.
