### ISSUE TITLE
Data source data "nsxt_ns_groups" "map" { } is not working in version 3.2.8

### ISSUE THREAD

**Issue by Nareshcbit** [vmware/terraform-provider-nsxt#776]
### Describe the bug

Error: This data source is not supported with given provider settings
│ 
│   with data.nsxt_ns_groups.map,
│   on main.tf line 34, in data "nsxt_ns_groups" "map":
│   34: data "nsxt_ns_groups" "map" {
│ 

### Reproduction steps

```bash
1. terraform {
  required_providers {
    nsxt = {
      source = "vmware/nsxt"
      version = "3.2.8"
    }
  }
}
2. data "nsxt_ns_groups" "map" {
}
3. run terraform plan

...
```

### Expected behavior

This data source is expected to build a "name to uuid" map of the whole NS Group table.

**Comment by annakhm** [comment]
Hi @Nareshcbit, are you running against VMC environment? Manager resources are not supported on VMC.

**Comment by Nareshcbit** [comment]
@annakhm yes I am running against VMC.

Any idea if it is supported in the future releases? Because, if it is coming soon we would like to use the native data resources than using custom approaches.

**Comment by annakhm** [comment]
Last time we checked, VMC did not support Manager API that is required to expose Manager objects in the provider (as opposed to policy objects). 
Would you be happy to use `nsxt_policy_groups` data source if it existed? This could be a feature request.
