### ISSUE TITLE
Wrong line indentation in the nsxt_policy_segment documentation

### ISSUE THREAD

**Issue by BergCyrill** [vmware/terraform-provider-nsxt#780]
### Describe the bug

In the documentation for the nsxt_policy_segment resource is a wrong indentation of required attributes:
...
* dhcp_option_121 - (Optional) DHCP classless static routes.
* network - (Required) Destination in cidr format.
* next_hop - (Required) IP address of next hop.
* dhcp_generic_option - (Optional) Generic DHCP options.
* code - (Required) DHCP option code. Valid values are from 0 to 255.
* values - (Required) List of DHCP option values.

...

Should be:
...
* dhcp_option_121 - (Optional) DHCP classless static routes.
  * network - (Required) Destination in cidr format.
  * next_hop - (Required) IP address of next hop.
* dhcp_generic_option - (Optional) Generic DHCP options.
  * code - (Required) DHCP option code. Valid values are from 0 to 255.
  * values - (Required) List of DHCP option values.

...

### Reproduction steps

```bash
1. follow documentation
```

### Expected behavior

Right indentation in the documentation

**Comment by tenthirtyam** [comment]
Looks correct in the markdown..

https://github.com/vmware/terraform-provider-nsxt/blob/866e72278ce144c181fb6750c6ce976f5f3effda/website/docs/r/policy_segment.html.markdown?plain=1#L74-L79

But it's not rendering correctly on the Terraform Registry.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by annakhm** [comment]
Yes indeed its a rendering issue, the markdown is correct.
