### ISSUE TITLE
nsxt_policy_vm_tags fails to refresh/find any VMs if there is one VM with broken tags

### ISSUE THREAD

**Issue by bernd-reize** [vmware/terraform-provider-nsxt#781]
### Describe the bug

Provider fails to refresh the state and/or can fail to import a new VM with tags.

Any activity that uses the function listAllPolicyVirtualMachines() such as refresh state or read all for a "terraform import nsxt_policy_vm_tags ..." fails if one VM exists with broken tags. Broken tag means a tag where only the field scope is set but not the field tag.

A manually created VM outside of terraform scope but with broken tags triggers the failure condition in listAllPolicyVirtualMachines() and thereby prevents the provider to find any VM.

### Reproduction steps

```bash
1. Create a new VM in a vSphere/NSX-T environment
2. In NSX-T apply a tag for this VM where only the field "scope" is set. But the field "tag" remains unset
4. Query the NSX-T API manually and verify that /api/v1/fabric/virtual-machines returns the list of VMs with the tag section for above VM as: tags: [ { "scope": "testscope" } ]
3. Try to refresh the state in terraform with existing VMs that have tags
4. Provider fails with [INFO] Error reading Virtual Machines when looking for ID:
```

### Expected behavior

Any broken objects returned by NSX-T should be ignored by the provider unless that particular object is under terraform control.
After encountering the erroneous object the provider should continue reading all remaining valid resources

### Additional context

Note: issue is related to pagination. An error encountered while reading a page will return all results received so far. But will not continue to read the remaining pages and thereby potentially miss a lot of resources

**Comment by annakhm** [comment]
Hi @bernd-reize, what version of NSX are you using? I don't seem to be able to reproduce the error you're seeing.

**Comment by bernd-reize** [comment]
Hi @annakhm, our environment is using NSX-T 3.1.3.7

**Comment by annakhm** [comment]
Thanks for responding. I still wasn't able to see this happening locally, so could you please provide debug logs (set TF_LOG="debug")

**Comment by annakhm** [comment]
Please reopen with logs if reproduced, thank you!
