### ISSUE TITLE
Importing nsxt_ns_group fail to import IPAddressExpression and ConjunctionOperator

### ISSUE THREAD

**Issue by AxFrancois** [vmware/terraform-provider-nsxt#791]
### Describe the bug

Hello,

I just made an Issue but I have another one worth signaling. Once again, I want to import security groups from our existing infrastructure into terraform. When trying to import the security group as nsxt_ns_group, the conditions on group attribution aren't correctly imported, the conditions on IP addresses (IPAddressExpression) and logical operator (ConjunctionOperator) are absents of the tfstate file.

Also I import the rule as nsxt_policy_group and got this error :
```
C:\Users\User1\Documents\Codes\Terraform>terraform import nsxt_policy_group.group1 00d7650d-cf4d-4bca-82cc-32a719790a80
nsxt_policy_group.group1: Importing from ID "00d7650d-cf4d-4bca-82cc-32a719790a80"...
nsxt_policy_group.group1: Import prepared!
  Prepared nsxt_policy_group for import
nsxt_policy_group.group1: Refreshing state... [id=00d7650d-cf4d-4bca-82cc-32a719790a80]
╷
│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to "nsxt_policy_group.group1", the provider detected that no object exists with the given id. Only pre-existing objects can be 
│ imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this
│ resource.
╵
```

So I guess I don't have other choice that to use nsxt_ns_group
We are using VMware NSX-T 3.2.0.1.0.19232396 and vmware/nsxt 3.2.8 for terraform.

### Reproduction steps

1. Use the NSXT API to get the security groups and their ID.
```JSON
{
    "expression" : [ {
      "paths" : [ "mypath/securitygroup-30" ],
      "resource_type" : "PathExpression",
      "id" : "530d6c55-ecda-4915-9879-0fb1c5b82793",
      [...]
    }, {
      "conjunction_operator" : "OR",
      "resource_type" : "ConjunctionOperator",
      "id" : "2f296394-c09e-4608-8466-b701571c7881",
       [...]
    }, {
      "member_type" : "VirtualMachine",
      "external_ids" : [ "501ac723-8880-fc21-656e-e8593c308055" ],
      "resource_type" : "ExternalIDExpression",
      "id" : "34878786-9c34-427e-8892-2570388be801",
       [...]
    }, {
      "conjunction_operator" : "OR",
      "resource_type" : "ConjunctionOperator",
      "id" : "94440bd5-ff46-47ee-b9fc-eb0e94cb1f13",
      [...]
    }, {
      "ip_addresses" : [ "192.168.0.0/16" ],
      "resource_type" : "IPAddressExpression",
      "id" : "7ee9add5-ae90-499a-8092-b6e55b6b915e",
      [...]
    } ],
    [...]
    "unique_id" : "00d7650d-cf4d-4bca-82cc-32a719790a80",
    [...]
  }
```
2. Create the ressource in your .tf file
```terraform
resource "nsxt_ns_group" "group3" {

}
```
3. Import the ressource to terraform
```Shell
C:\Users\User1\Documents\Codes\Terraform>terraform import nsxt_ns_groupgroup3 00d7650d-cf4d-4bca-82cc-32a719790a80
nsxt_ns_group.group3: Importing from ID "00d7650d-cf4d-4bca-82cc-32a719790a80"...
nsxt_ns_group.group3: Import prepared!
  Prepared nsxt_ns_group for import
nsxt_ns_group.group3: Refreshing state... [id=00d7650d-cf4d-4bca-82cc-32a719790a80]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
4. Go to the tfstate file and see that member is incorrect
```JSON
[...]
"resources": [
    {
      "mode": "managed",
      "type": "nsxt_ns_group",
      "name": "group3",
      "provider": "provider[\"registry.terraform.io/vmware/nsxt\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "description": "blablabla",
            "display_name": "MySG",
            "id": "00d7650d-cf4d-4bca-82cc-32a719790a80",
            "member": [
              {
                "target_type": "NSGroup",
                "value": "558dd921-3be2-44c4-ab38-67e8398542fc"
              },
              {
                "target_type": "VirtualMachine",
                "value": "501ac723-8880-fc21-656e-e8593c308055"
              },
            ],
            "membership_criteria": [],
            [...]
        }
    }
  ]
}
```

### Expected behavior

The OR is technically implicit so this isn't really a bug, but the fact that the object is absent is annoying. 
The missing IP range should be correctly added, maybe like so : 
```
              {
                "target_type": "IPAddressExpression",
                "value": "7ee9add5-ae90-499a-8092-b6e55b6b915e"
              },
```

**Comment by annakhm** [comment]
Hi @AxFrancois, can you please specify full NSXT API you are using, including the URI?
If you're importing `nsxt_policy_group`, it would expect a policy object on NSX `/policy/api/v1/infra/domains/..`, rather than manager group object. We advise against using non-policy objects in terraform when possible.

**Comment by AxFrancois** [comment]
Hi @annakhm and thanks for your answer. 

The URI used is https://nsx.mycompany.ch/policy/api/v1/infra/domains/default/groups
Just to be clear, I tried to import the security groups as security policy as a desperate attempt, and this unsurprisingly didn't work, because while reading the nsxt terraform doc I realized nsxt_policy_group was similar to the security group I had (with criteria and conditional statement). 
It was just an workaround attempt and this don't solve the root issue that nsxt_ns_group import is simply broken for groups with conditional statements and ip adress expression.

**Comment by AxFrancois** [comment]
Good morning/afternoon. 

After some experimentation I finally found a way to bypass this issue using ```nsxt_policy_group```. 
Things is that NSXT is made of a lot of spaghetti code and I had to find a solution by trial and error. 
Last time we left I saw but didn't understood why there is to id field in the object description : ```id```, ```unique_id``` (and ```realization_id``` also but from my tests ```unique_id``` and ```realization_id``` always have the same values so whatever)

Turns out that those 2 IDs are indeed different and can produce some wonderful magic : 
- when using the ```unique_id```, you can import as a ```nsxt_ns_group```, this is what I did before and it's okay.
- when using the ```id```, you can import as a ```nsxt_policy_group``` ! 
And then because ```nsxt_policy_group``` have supports IP address and logical operator, everything is correctly described. Wonderful.
Thanks for the help.
