### ISSUE TITLE
New Attribute uplink_interface_ips for Ressource/Data-Source nsxt_policy_tier1_gateway

### ISSUE THREAD

**Issue by benzander** [vmware/terraform-provider-nsxt#793]
### Is your feature request related to a problem? Please describe.

In order to configure VRF Route Leaking the IPv4 / IPv6 Address of the T1 Gateways uplink Interface is required. Here the link to the NSX-T Dokumentation: https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.2/administration/GUID-6DF4F3CC-17DC-4F44-ACEE-D8771D6675F1.html

At present I have no possibility to find the Uplink IPs of the T1 Gateway with Terraform, hence I have to first create a T1, find the IP in the NSX-T GUI / CLI and then add static routes with the Ressource nsxt_policy_static_route.

### Describe the solution you'd like

It would be very helpful if the Ressource and Data Source: nsxt_policy_tier1_gateway would have an attribute that returns a map with the IPv4 Address and the IPv6 Address of the tier 1 gateways uplink interface.

**Comment by annakhm** [comment]
I think those IPs are exposed as part of extended_attributes of `GenericPolicyRealizedResource` which is part of Tier1 realization API. We will add those attribute to `nsxt_policy_realization_info` data source.
