### ISSUE TITLE
Route-map with set block sets local preference and MED to 0 by default

### ISSUE THREAD

**Issue by ens-scmeeu** [vmware/terraform-provider-nsxt#813]
### Describe the bug

When using an `nsxt_policy_gateway_route_map` resource with a `set` block, but without explicitly setting `local_preference`, local preference will be set to 0. It appears from looking at the [source code](https://github.com/vmware/terraform-provider-nsxt/blob/master/nsxt/resource_nsxt_policy_gateway_route_map.go#L201) that it is not conditionally set as I would expect, but always set in the presence of a `set` block. My assumption is that this structure is using a default value of 0 for local preference, which then causes it to be incorrectly modified.

UPDATE: The same issue applies to med. It should not be being reset either unless explicitly set. See below for a possible (but not quite ideal) fix.

### Reproduction steps

1. Create a base NSX-T setup with at least one operational BGP neighbor
2. Add an `nsxt_policy_gateway_route_map` with a `set` block, matching all routes. Do not set `local_preference`.
3. Attach route-map to `nsxt_policy_bgp_neighbor` in `route_filtering` block via `in_router_filter`
4. In T0 BGP table, observe that the received routes have a local preference of 0 (it should be 100)

### Expected behavior

When not explicitly set in the route-map, BGP local preference should not be set. All implementations I'm aware of (including NSX-T) will then set local preference to 100 by default on receipt of the route (for eBGP neighbors that is, iBGP neighbors will preserve the existing value of the attribute).

**Comment by annakhm** [comment]
Thanks for reporting this @ens-scmeeu! Also appreciate your fix suggestion, however I'd rather not set a `-1` default on terraform side to avoid non-empty diff. A fix I suggest would mark these attributes as `Computed` and not set those unless explicitly specified.
