### ISSUE TITLE
nsxt_policy_ip_address_allocation can cause address conflict

### ISSUE THREAD

**Issue by benzander** [vmware/terraform-provider-nsxt#817]
### Describe the bug

It is possible to request IPs which is already in use with the allocation_ip attribute 
The NSX-T Gui shows an error but there is no possibility to see that with terraform. Terraform apply works without any error and I can access the allocation_ip attribute which returns the IP that is already in use.

It is also possible to request IPs which are not part of the pool.

### Reproduction steps

Apply this example code:
```
resource "nsxt_policy_ip_pool" "ipPool-test" {
  display_name = "ipPool-test"

}

resource "nsxt_policy_ip_pool_static_subnet" "static_subnet1" {
  display_name = "Internet-Test"
  pool_path    = nsxt_policy_ip_pool.ipPool-test.path
  cidr         = "12.12.12.0/24"

  allocation_range {
    start = "12.12.12.10"
    end   = "12.12.12.20"
  }

}


resource "nsxt_policy_ip_address_allocation" "test1" {
  display_name = "test"
  description  = "Terraform provisioned IpAddressAllocation"
  pool_path    = nsxt_policy_ip_pool.ipPool-test.path
}
resource "nsxt_policy_ip_address_allocation" "test2" {
  display_name = "test"
  description  = "Terraform provisioned IpAddressAllocation"
  pool_path    = nsxt_policy_ip_pool.ipPool-test.path
}
resource "nsxt_policy_ip_address_allocation" "test3" {
  display_name  = "test"
  description   = "Terraform provisioned IpAddressAllocation"
  pool_path     = nsxt_policy_ip_pool.ipPool-test.path
  allocation_ip = "12.12.12.10"
}
resource "nsxt_policy_ip_address_allocation" "test4" {
  display_name  = "test"
  description   = "Terraform provisioned IpAddressAllocation"
  pool_path     = nsxt_policy_ip_pool.ipPool-test.path
  allocation_ip = "12.12.12.30"
}
```
Use Terraform Console:
tf console
> nsxt_policy_ip_address_allocation.test1.allocation_ip
"12.12.12.10"
> nsxt_policy_ip_address_allocation.test2.allocation_ip
"12.12.12.11"
> nsxt_policy_ip_address_allocation.test3.allocation_ip
"12.12.12.10"
> nsxt_policy_ip_address_allocation.test4.allocation_ip
"12.12.12.30"

You see that that test3 returns "12.12.12.10" which is already allocated by test1.
Test3 returns "12.12.12.30" which is not part of the configured allocation range.

### Expected behavior

I would expect an error for test3 and test4 during the terraform plan or at least during the terraform apply.

### Additional context

The NSX Manager shows errors for test3 and test4:
![NSX-T-Manager-Screenshot](https://user-images.githubusercontent.com/99820917/204593797-b66f5d06-3a93-46e3-9e0f-53700fe7e409.jpg)

**Comment by annakhm** [comment]
Hi @benzander, have you considered using [nsxt_policy_realization_info](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/data-sources/policy_realization_info) data source to check if the allocation was successful?

**Comment by benzander** [comment]
Hi @annakhm,
thank you for you advise and sorry for my late response.

I was not aware of the [policy realization info](https://registry.terraform.io/providers/vmware/nsxt/latest/docs/data-sources/policy_realization_info) data source.
It's kind of strange to build a resource and use an additional data source to check if the resource creation was successful. I would expect the TF Provider to check if the resource creation as successful.

But anyway... we've tested if that could be a solution.
The data source is able to identify the failed allocation state. So it would be possible to write a terraform module that uses the resource to allocate an IP and check with the data source whether it was successful. But there are some significant limitations.

Sometimes the NSX Manager takes some time (a few minutes) while the allocation status says "Failed" until the allocation status turns "Success".  As the data source checks the Allocation status at as specific time it will collect "Failed".
So the only solution would be to set a few minutes delay in the data source. That would slow down the apply a lot if we are using a few Allocations.

But we also noticed that changing display name or description of nsxt_policy_ip_address_allocation would cause a redeployment and change of allocated IP. And that is a no got for IPAM :-)
So we decided to use another solution.

At the End of the Day my finding was not a bug. It seems to be expected behaviour. :-)

**Comment by annakhm** [comment]
Hi @benzander, the provider would report successful creation of resource if the create API resulted in 200 OK. Realization of the resource is a separate asynchronous process that can take some time, hence we decided not to block the provider with waiting for realization, rather offer a separate data source for configs that are interested in realization. So this behavior is by design.
I was not aware that NSX would respond with `Failed` realization while still trying. This indeed creates an issue with realization check. Thank you for reporting this. We'll open a separate bug to track this.
I'll keep this one open for now to investigate the display_name/description problem.
