### ISSUE TITLE
Support for NSXT version 4 

### ISSUE THREAD

**Issue by olivierHa** [vmware/terraform-provider-nsxt#824]
### Is your feature request related to a problem? Please describe.

Is this provider compatible with the nsxt 4.0 version released on 08/2022 ?

### Describe the solution you'd like

Support for NSXT 4.0.*

**Comment by annakhm** [comment]
Hi @olivierHa, yes the provider is compatible with 4.0 line. We'll update the README to reflect this.

**Comment by olivierHa** [comment]
Thanks for the confirmation !
