### ISSUE TITLE
Support dynamic group in group memberships based on tags

### ISSUE THREAD

**Issue by benzander** [vmware/terraform-provider-nsxt#828]
### Is your feature request related to a problem? Please describe.

I want to prepare firewall rules in one terraform module that e.g. allows ipsec traffic on a T0 VRF and add the VPN Endpoint IP Address of the T1 dynamically in a different terraform Module.

I'm missing to features in the NSX-T Provider to do that.

### Describe the solution you'd like

1. The ressource nsxt_policy_group needs to support "IP Addresses Only" Groups

2. nsxt_policy_group needs to support criteria type "group" like that:
```
resource "nsxt_policy_group" "vpn-endpoints" {
  display_name = "vpn-endpoints"

  criteria {
    condition {
      key         = "Tag"
      member_type = "group"
      operator    = "EQUALS"
      value       = "vpn|endpoint"
    }
  }
}
```

### Describe alternatives you've considered

If it is easier to implement a new ressource to create IP Addresses Only groups I could also work with that.
E.g. nsxt_policy_ip_group

**Comment by tvigneron** [comment]
Hello Benzander,

Can you please clarify why you want to support a Group "IP Addresses Only", and not just use a "Generic" group with IP addresses?

Somthing like:

resource "nsxt_policy_group" "group1" {
  display_name = "tf-group1"
  description  = "Terraform provisioned Group"

  criteria {
    ipaddress_expression {
      ip_addresses = ["211.1.1.1", "212.1.1.1", "192.168.1.1-192.168.1.100"]
        }
  }
}

**Comment by yasvanth** [comment]
As `nsxt_ip_set` resource is deprecated,  either `member_type = group` would be best to tag the GW addresses dynamically.  Would this be writing a new resource or an update to the existing policy group because NSX UI doesn't have the option to set member criteria as "group"
