### ISSUE TITLE
We are using Terraform to manage NSX 4 Network Firewall's rules. However, Terraform is changing the resource rule order when passing it to NSX.

### ISSUE THREAD

**Issue by Microbuse** [vmware/terraform-provider-nsxt#830]
### Describe the bug

When Create Security Policie Environment from .tf file order.

resource "nsxt_policy_security_policy" "outbound_nsx" {.......
resource "nsxt_policy_security_policy" "port443_allow_isolate_zone" {......
resource "nsxt_policy_security_policy" "drop_isolate_zone" {........

It gets added in wrong order. Looks like it adds them randomly.
outbound_nsx
drop_isolate_zone
port443_allow_isolate_zone

If you then add one more resource
resource "nsxt_policy_security_policy" "smb_allow_isolate_zone" {......

Order is then 
outbound_nsx
drop_isolate_zone
smb_allow_isolate_zone
port443_allow_isolate_zone

Can´t figure it out, it is not based on Alphabet letters.

If you set sequence_number = 1,2, 3, 4 it works.
resource "nsxt_policy_security_policy" "outbound_nsx" { sequence_number = 1010
resource "nsxt_policy_security_policy" "port443_allow_isolate_zone" { sequence_number = 1020
resource "nsxt_policy_security_policy" "smb_allow_isolate_zone" { sequence_number = 1030
resource "nsxt_policy_security_policy" "drop_isolate_zone" { sequence_number = 1040

Order is then
outbound_nsx
port443_allow_isolate_zone
smb_allow_isolate_zone
drop_isolate_zone

But when you have 2000 resources this gets really messy.
And it will not get easy to insert a resource in between sequence_number = 1019 and 1020 and 1021  
Then you need to rearrange all below sequence_number.

It would have worked if it was possible to have like 1020.1 and 1020.2
But best of all, if it honors the .tf rule order always.

   

### Reproduction steps

1. add 3 resource groups
2. Check and compare NSX firewall security-policies order list vs .tf order list
3. add 1 more resource group
4. Check and compare NSX firewall security-policies order list vs .tf order list
5. test to add the sequence_number  on all your firewall resource groups
resource "nsxt_policy_security_policy" "drop_isolate_zone" {
    sequence_number = xxx

### Expected behavior

Like to have the same firewall security-policies order as it is added in the .tf file.

### Additional context

All networking devices will process packets against these terms, from top to bottom.

**Comment by annakhm** [comment]
Hi @Microbuse, order of resources in terraform config does not ensure any ordering on the backend. When ordering security policies, it is recommended to leave gaps in sequence numbers for the sake of future inserts. This is also what UI does if I'm not mistaken.

**Comment by Microbuse** [comment]
Yes, NSX UI is handel this by it´s on when you re arrange the rules. Can´t Terraform manage the sequence numbers automatically? When you have more then 2000 resources it gets messy to handel when you run it automatically deployments?

**Comment by annakhm** [comment]
With ordered resources, the resource order needs to be defined by the user, as the provider doesn't have any other reliable indication.

**Comment by Microbuse** [comment]
Is this not the same problem and with a solution?
https://github.com/hashicorp/terraform-provider-aws/issues/24977

**Comment by Microbuse** [comment]
> With ordered resources, the resource order needs to be defined by the user, as the provider doesn't have any other reliable indication.

Is it not possible to have a PolicyRule.tf and that terraform reads the file in resource order and generate a sequence_numbers based on order.
Then when you add a new rule someware in the file it gets added and gets correct sequence number and all rules below only get new ascending numbers. Sequence number can be force updated.

**Comment by annakhm** [comment]
Sorry for the delayed response.
No, the example you provided deals with set of rules that are defined as part of a resource:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_rule_group
For lists/sets of objects defined within parent resource, we can control whether terraform sees this list as ordered or unordered group of objects.
However, the root-level objects - such as `nsxt_policy_security_policy` are not seen as terraform as ordered list and are in fact parallelized when executed (unless terraform detects a dependency between those). So as a provider, we have no indication in which order terraform itself will evaluate and execute those objects.
Hope it makes sense!

**Comment by annakhm** [comment]
Closing this, please reopen if further discussion could be helpful.
