### ISSUE TITLE
Default firewall policy of route-based VPN tunnel cannot be modified in TF apply that creates the resource "nsxt_policy_ipsec_vpn_session"

### ISSUE THREAD

**Issue by hbechtel** [vmware/terraform-provider-nsxt#851]
### Describe the bug

When building a route-based VPN session NSX-T automatically creates a default firewall policy to allow network traffic though the tunnel. I would like to change this rule from"Allow" to "Drop".

When I create a route-based VPN tunnel using the resource "nsxt_policy_ipsec_vpn_session" and change the default behavior of this default firewall policy TF shows an error message when applying the changes:

│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.T1.nsxt_policy_predefined_gateway_policy.gwFW-predefinedGatewayPolicy to include new values learned so far during apply, provider
│ "registry.terraform.io/vmware/nsxt" produced an invalid new value for .default_rule[0].scope: was
│ cty.StringVal("/infra/tier-1s/85722363-9982-4689-be85-7fd31f8754ae/ipsec-vpn-services/281ef7fe-e2f0-4a00-a4e9-296db7e3da73/sessions/ff0a171f-6bae-4919-9a81-38cdc5c690c3"), but now
│ cty.StringVal("/infra/tier-1s/85722363-9982-4689-be85-7fd31f8754ae/ipsec-vpn-services/281ef7fe-e2f0-4a00-a4e9-296db7e3da73/sessions/345b8c39-6a45-49a5-9ab9-7fd56e08fb2d").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
The VPN session is built and the default firewall policy gets created, but the change of the action from allow to drop fails.

When executing a second TF apply the default firewall policy gets changed as desired.

### Reproduction steps

1. Build up a T1 gateway
2. Configure VPN resources
``
data "nsxt_policy_gateway_locale_service" "gwLocaleService" {
  gateway_path = nsxt_policy_tier1_gateway.T1.path
}

resource "nsxt_policy_ipsec_vpn_service" "vpn_service" {
  display_name        = "VPN-Service-Name"
  locale_service_path = data.nsxt_policy_gateway_locale_service.gwLocaleService.path
  enabled             = true
  ha_sync             = true
}

resource "nsxt_policy_ipsec_vpn_local_endpoint" "local_endpoint" {
  display_name  = "Local-Endpoint-Name"
  service_path  = nsxt_policy_ipsec_vpn_service.vpn_service.path
  local_address = "4.3.2.1"
  local_id      = "4.3.2.1"
}

resource "nsxt_policy_ipsec_vpn_session" "vpn_session_route" {
   service_path               = nsxt_policy_ipsec_vpn_service.vpn_service.path
   local_endpoint_path        = nsxt_policy_ipsec_vpn_local_endpoint.local_endpoint.path
   display_name               = "Route-based-tunnel"
   compliance_suite           = "NONE"
   peer_address               = "1.2.3.4"
   peer_id                    = "1.2.3.4"
   authentication_mode        = "PSK"
   psk                        = "1234567890abcdefghij"
   connection_initiation_mode = "INITIATOR"
   enabled                    = "enabled"
   vpn_type                   = "RouteBased"
   ip_addresses               = ["169.254.252.1"]
   prefix_length              = 30
}

resource "nsxt_policy_predefined_gateway_policy" "predefinedGatewayPolicy" {
"default_rule" {
    content {
      scope     = replace(nsxt_policy_ipsec_vpn_session.vpn_session_route.path, "locale-services/default/", "")
      logged    = true
      action    = "DROP"
    }
  }
}
``

3. Apply the changes shown in bullet point 2

### Expected behavior

I expect that the configuration gets applied completely, without error messages and differences between plan and realisation.

### Additional context

While testing the VPN resources I found that "nsxt_policy_ipsec_vpn_session.vpn_session_route.path" returns a value like "/infra/tier-1s/85722363-9982-4689-be85-7fd31f8754ae/locale-services/default/ipsec-vpn-services/281ef7fe-e2f0-4a00-a4e9-296db7e3da73/sessions/ff0a171f-6bae-4919-9a81-38cdc5c690c3". When I address the VPN session I need to use the path
"/infra/tier-1s/85722363-9982-4689-be85-7fd31f8754ae/ipsec-vpn-services/281ef7fe-e2f0-4a00-a4e9-296db7e3da73/sessions/ff0a171f-6bae-4919-9a81-38cdc5c690c3" (without "locale-services/default/"), which is the same path that the Web UI shows. Why is there this difference in the path?

**Comment by annakhm** [comment]
Hi @hbechtel, unfortunately I was not able to reproduce the problem based on the steps provided.
My config for default policy included both default rules though:

```
resource "nsxt_policy_predefined_gateway_policy" "predefinedGatewayPolicy" {
  path = data.nsxt_policy_gateway_policy.default.path
  default_rule {
       scope = replace(nsxt_policy_ipsec_vpn_session.vpn_session_route.path, "locale-services/default/", "")
       logged = true
       action = "DROP"
  }

  default_rule {
       action          = "ALLOW"
       scope           = nsxt_policy_tier1_gateway.test.path
  }
} 
```

Judging by the error above, my guess is that the error could be a result of several iterations of config apply that involved different VPN session ids. Could you please confirm if the problem reproduces for you with clean config (VPN & GW policy defined from scratch)? Thank you!

**Comment by hbechtel** [comment]
Hi @annakhm, unfortunately I also wasn't able to reproduce the problem, neither in the original environment nor in a new/clean environment. We assume that the problem was related to and caused by some other configuration issues in our DEV environment which were solved in the meantime. Sorry for the inconvinience and thanks for your efforts.
