### ISSUE TITLE
Updates on "nsxt_policy_tier1_gateway" ressource results in "Not Set" ha mode for tier-1 in nsx-t manager

### ISSUE THREAD

**Issue by m-garrido** [vmware/terraform-provider-nsxt#852]
### Describe the bug

When we update a tier-1 gateway ressource by terraform, in nsx-t manager webui, the "ha mode" is set to "Not Set".
However, the tier-1 hasn't change is mode as is always in "Active-Standby" mode. In order to recover the value, edit/save without changes.

### Reproduction steps

Create a change in a "nsxt_policy_tier1_gateway" ressource and apply with terraform.
See in the webui nsx-t manager tier-1 the "ha mode" state.

### Expected behavior

In the webui nsx-t manager, the tier-1 must show the expected value for "ha mode".

### Additional context

The issue could be from nsx-t and not from terraform nsx-t provider.

**Comment by RawKitn** [comment]
Hi Mika, thx for your help, we had drift yesterday and could not find out what causing this behaviour <3
