### ISSUE TITLE
Missing group_type definition for nsxt_policy_group

### ISSUE THREAD

**Issue by laurentmas** [vmware/terraform-provider-nsxt#855]
### Describe the bug

In VMC on AWS 1.20v2 with nsx 4.0.1.52.0.20682514 , a new argument has been added when we create a Management Gateway policy group.

Now by default groups are created with IP Addresses Only Type instead of Generic.

On terraform provider, group_type parameter is missing so we cannot specify the type when using it.
If we want to update a Management Group that has been created manually or by VMC, we cannot until we remove them

group_type:  (Array<string>)
Group type can be specified during create and update of a group.
Empty group type indicates a 'generic' group, ie group can
include any entity from the valid GroupMemberType.

### Reproduction steps

1. Manually creates a Group Test on management Gateway on VMC on AWS 1.20
2. Add an ipaddress into the group and save it.
3. Try to Update the Group using terraform by adding a new ip address; 
4. Terraform Apply

Terraform with fails with the following error :
│ Error:  Failed to update Group Test: Invalid Group Member type update. [IPAddress] type cannot be updated to Generic type. (code 500336)
...

### Expected behavior

We should be allowed to specify group_type as IPAddress and other supported group types.

If no group_type is specified, it must creates a generic group as the current behavior.

**Comment by annakhm** [comment]
Hi @carsonpadawon, we are aware of this issue (its VMC-specific) and working on the fix. Thanks for reporting!
