### ISSUE TITLE
nsxt_policy_service - add support for NestedServiceServiceEntry resource_type

### ISSUE THREAD

**Issue by bjwebster** [vmware/terraform-provider-nsxt#858]
### Is your feature request related to a problem? Please describe.

NSX services can contain other services in a nested structure but the Terraform provider does not support this. The resource_type is: NestedServiceServiceEntry.

All of the other resource_types are supported i.e. IPProtocolServiceEntry, IGMPTypeServiceEntry, ICMPTypeServiceEntry, ALGTypeServiceEntry, L4PortSetServiceEntry, EtherTypeServiceEntry.

Can support for this resource_types be added?

### Describe the solution you'd like

Add support for resource_type NestedServiceServiceEntry. 

### Describe alternatives you've considered

It would be possible to add the individual services to policy rules but this is an inefficient way of achieveing the aim if there are a number of rules that use the same group of services.

**Comment by annakhm** [comment]
Hello, this feature was recently added here https://github.com/vmware/terraform-provider-nsxt/pull/836 by @AxFrancois. Not released yet (next release will likely be in April). Hope this helps!
