### ISSUE TITLE
Add support for nested security group in security group definition.

### ISSUE THREAD

**Issue by Nareshcbit** [vmware/terraform-provider-nsxt#859]
### Is your feature request related to a problem? Please describe.

In NSX a security group can have other security groups as its members. However, Terraform doesn't support it.
Currently, it allows only VirtualMachine, VirtualNetworkInterface, CloudNativeServiceInstance, or PhysicalServer as members.

### Describe the solution you'd like

Allow "SecurityGroup" as member_type for external_id_expression criteria in nsxt_policy_group_definition

resource "nsxt_policy_group" "group1" {
  display_name = "tf-group1"
  description  = "Terraform provisioned Group"
  criteria {
    external_id_expression {
      **member_type  = "SecurityGroup"**
      external_ids = ["520ba7b0-d9f8-87b1-6f44-15bbeb7935c7", "52748a9e-d61d-e29b-d54b-07f169ff0ee8-4000"]
    }
  }

### Describe alternatives you've considered

There is no alternative to achieve it through Terraform

### Additional context

<img width="877" alt="image" src="https://user-images.githubusercontent.com/15374172/227786759-225f9af3-2c69-447c-ad25-eba0fc0ba70d.png">

**Comment by benzander** [comment]
@Nareshcbit: Static assigment of one Group to another group is possible via terraform. Here how that looks like:

```
resource "nsxt_policy_group" "group" {
  display_name = "group"
  
  criteria {
    path_expression {
          member_paths = [nsxt_policy_group.nestedGroup.path]
    }
  }
}
```

The TF Provider is only missing dynamic group in group memberships: https://github.com/vmware/terraform-provider-nsxt/issues/828

**Comment by annakhm** [comment]
Hello @Nareshcbit, I don't see `SecurityGroup` is one of the options for `member_type` in[ latest NSX spec](https://developer.vmware.com/apis/1583/nsx-t):

member_type | External ID member type | string | RequiredEnum: VirtualMachine, VirtualNetworkInterface, CloudNativeServiceInstance, PhysicalServer
