### ISSUE TITLE
nsxt_policy_gateway_dns_forwarder - argument "Cache Size" is missing

### ISSUE THREAD

**Issue by mr-arzt** [vmware/terraform-provider-nsxt#887]
### Is your feature request related to a problem? Please describe.

Hello all,

i miss the option to configure the "Cache Size" which is available over the WebGUI.

https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_gateway_dns_forwarder

Best,
Dominic

### Describe the solution you'd like

Add the argument cache_size

**Comment by alagoutte** [comment]
flag good for first issue ? 

need to add cache_size (int) on this schema https://github.com/vmware/terraform-provider-nsxt/blob/eac3a63a509358d66332a75a998c54a07206fa3b/nsxt/resource_nsxt_policy_gateway_dns_forwarder.go#L39 (or using the new diff tools ? @annakhm )

**Comment by annakhm** [comment]
Hi @alagoutte, this PR is already out https://github.com/vmware/terraform-provider-nsxt/pull/889
