### ISSUE TITLE
Please update the documentation about "df_policy" in policy_ipsec_vpn_tunnel_profile

### ISSUE THREAD

**Issue by mr-arzt** [vmware/terraform-provider-nsxt#893]
### Is your feature request related to a problem? Please describe.

Hello,

i don`t find any information in the "[Argument Reference]" about df_policy

https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_ipsec_vpn_tunnel_profile

Best,
Dominic

### Describe the solution you'd like

Please add a short description and default value (Optional or not)

**Comment by annakhm** [comment]
Thank you for letting us know, this is now fixed
