### ISSUE TITLE
nsxt_policy_gateway_qos_profile resource

### ISSUE THREAD

**Issue by dmbuil** [vmware/terraform-provider-nsxt#896]
### Is your feature request related to a problem? Please describe.

There is no Resource for Gateway QoS Profile, only a Data source, `nsxt_policy_gateway_qos_profile`.
I intend to use it to _bulk create_ QoS profiles for T1, as they must be created all the same across several NSX-T instances.

### Describe the solution you'd like

A new resource, `nsxt_policy_gateway_qos_profile` to manage the Gateway QoS Profiles.

### Describe alternatives you've considered

none, as it is not implemented.

**Comment by dmbuil** [comment]
Never mind, I've seen that it is covered in #881

**Comment by annakhm** [comment]
Yes, next version of the provider with this resource will be released soon
