### ISSUE TITLE
Doc ip_version not rendered ok in documentation

### ISSUE THREAD

**Issue by dmbuil** [vmware/terraform-provider-nsxt#903]
### Describe the bug

Section `ip_version ` in latest documentation [here](https://registry.terraform.io/providers/vmware/nsxt/3.3.1/docs/resources/policy_security_policy#ip_version) is not rendered correctly in Terraform Registry website.

<img width="727" alt="Captura de Pantalla 2023-05-31 a las 23 07 07" src="https://github.com/vmware/terraform-provider-nsxt/assets/22377986/4e06572a-9314-4156-9579-073ecdf4ed46">

### Reproduction steps

1. Access [registry.terraform.io](https://registry.terraform.io)
2. Search for NSX-T Provider and find the resource `policy_security_policy`. 

### Expected behavior

It is a minor, cosmetic issue that does not cause major inconveniences.
But it should be rendered as follows:

---
 - [ip_version](https://registry.terraform.io/providers/vmware/nsxt/latest/docs#ip_version) - (Optional) Version of IP protocol, one of `NONE`, `IPV4`, `IPV6`, `IPV4_IPV6`. Default is `IPV4_IPV6`. For `Ethernet` category rules, use `NONE` value.
---

(I'd dare to say that there is a missing backtick right before the first IPV4).

**Comment by alagoutte** [comment]
> @alagoutte please create your PR on [vmware/terraform-provider-nsxt](https://github.com/vmware/terraform-provider-nsxt) instead of your [private fork](https://github.com/alagoutte/terraform-provider-nsxt), so we can merge this :)

Oups... fixed !
