### ISSUE TITLE
inconsistency between the NSX-T and the terraform unique ID. 

### ISSUE THREAD

**Issue by muneebhussain** [vmware/terraform-provider-nsxt#923]
### Describe the bug

In the NSX-T manager, the Unique ID for LB-VIPs-01 is recorded as 5a5ee9d9-4f76-4ac5-a9c4-6d2fadbe309d. However, when referencing LB-VIPs-01 in Terraform, the corresponding ID appears as aa8476a0-a040-4703-9eee-646753b1285a. And there is no reference of NSX-T ID 5a5ee9d9-*** in the state file.

 There is a discrepancy between the API response from NSX-T  and what's displayed in the UI? Does the NSX-T provider use an abstraction for tracking resources rather than a visible id in NSX-T?

How can I import the existing resource in the terraform state file since there is inconsistency in the ids and terraform won't import with the Id in the NSX-T manager?

![a7tPStjo2Q](https://github.com/vmware/terraform-provider-nsxt/assets/17991981/c98c2ff7-886e-4dd9-8b10-1345df2160c9)
![SL8Zw2KUMT](https://github.com/vmware/terraform-provider-nsxt/assets/17991981/6159a078-10fa-47a3-9929-ae3886d7bacf)

### Reproduction steps

1.
2.
3.
...

### Expected behavior

We expected to have the same segment IDs in the NSX-T manager and state file 

### Additional context

terraform {
  required_providers {
    nsxt = {
      source = "vmware/nsxt"
    }
  }
}

data "nsxt_policy_tier1_gateway" "tier1" {
  display_name = "tier1-gw"
}

resource "nsxt_policy_fixed_segment" "net_segment" {
  display_name      = var.segment_name
  description       = var.default_net_segment_description
  connectivity_path = data.nsxt_policy_tier1_gateway.tier1.path
  tag {
    tag   = "gcve_net_segments"
  }
  tag {
    tag   = var.environment_tag
  }

  subnet {
    cidr        = var.cidr_gateway
  }
}

**Comment by ksamoray** [comment]
Hi @muneebhussain, the screenshot attached is from the MP UI while the configured switch is for the Policy Manager.
The review the segment choose "POLICY" at the top right of the NSX UI and then from the topmost menu choose "Networking" and the "Segments" from the panel on the left.
In general, Policy objects could have different ids from the MP objects.
![Screenshot 2023-07-16 at 11 55 06](https://github.com/vmware/terraform-provider-nsxt/assets/9676139/df7337a8-082b-4d82-aaab-7c6298ba76f4)
