### ISSUE TITLE
Dependency Issue between nsxt_policy_service and nsxt_policy_security_policy / nsxt_policy_gateway_policy

### ISSUE THREAD

**Issue by benzander** [vmware/terraform-provider-nsxt#942]
### Describe the bug

The NSX TF Provider tries to delete nsxt_policy_service before removing it from nsxt_policy_security_policy or nsxt_policy_gateway_policy.

│ Error:  Failed to delete Service e949ef57-d0b8-43b5-822e-3e6a7fd220cb: The object path=[/infra/services/e949ef57-d0b8-43b5-822e-3e6a7fd220cb] cannot be deleted as either it has children or it is being referenced by other objects path=[/infra/domains/default/security-policies/4bef9a8b-858b-4712-b72d-23bfb8f9982b/rules/e0a6f406-179f-4eff-a789-c5b7cdfbc633] (code 500030)

### Reproduction steps

1. Apply this code:

`resource "nsxt_policy_service" "svc-test" {
  display_name = "svc-albVSIP-test"
  description  = "Autocreated Service Object by tf-mod-nsxalb-virtualServices Module" #später noch schicker machen

  l4_port_set_entry {
    protocol          = "TCP"
    destination_ports = ["9999"]
  }
}

resource "nsxt_policy_security_policy" "dFW-test" {
  display_name    = "dFW_alb"
  category        = "Environment"
  sequence_number = 1200

  rule {
    display_name       = "fwR-001"
    scope              = []
    source_groups      = []
    destination_groups = []
    action             = "DROP"
    services           = [nsxt_policy_service.svc-test.path]
    logged             = "true"
    disabled           = true
  }
}`

2. Change it

`resource "nsxt_policy_security_policy" "dFW-test" {
  display_name    = "dFW_alb"
  category        = "Environment"
  sequence_number = 1200

  rule {
    display_name       = "fwR-001"
    scope              = []
    source_groups      = []
    destination_groups = []
    action             = "DROP"
    services           = []
    logged             = "true"
    disabled           = true
  }
}`

### Expected behavior

The TF Provider needs to change the Firewall Policy before it deletes the service.

### Additional context

There is the same issue with the Distributed Firewall (nsxt_policy_security_policy) and the Gateway Firewall Ressource (nsxt_policy_gateway_policy).

If you try to remove the complete rule it triggers the same issue. Only deletion of the entire ressource nsxt_policy_security_policy / nsxt_policy_gateway_policy together with deletion of the service works.

**Comment by annakhm** [comment]
Hi @benzander, this sounds like https://registry.terraform.io/providers/vmware/nsxt/latest/docs/guides/faq#dependency-error-on-update-or-destroy. Its a terraform core thing, `lifecycle` directive solves it (as described in the FAQ entry). Hope this helps.

**Comment by benzander** [comment]
Hi @annakhm 
Nice... that seems to work just fine! :-)
That also helps us with renaming service or group resources with dependencies.

Can you make that default in the NSX-T Provider for specific resources?

**Comment by annakhm** [comment]
To the best of my knowledge, provider has no control over lifecycle.. We added the `lifecycle` directive to documentation sample for relevant resources though.

**Comment by annakhm** [comment]
Closing this
