### ISSUE TITLE
nsxt_policy_nat_rule does not work in M1.22v4

### ISSUE THREAD

**Issue by kremerpatrick** [vmware/terraform-provider-nsxt#977]
### Describe the bug

This same Terraform code has worked for years and appears to have been broken with the 1.22v4 SDDC release.

NAT rules deployed with Terraform do not seem to be activated until another NAT rule is manually published in the UI

I'm not sure if it's related or not, but calls to https://nsx-x.x.x.x.rp.vmwarevmc.com/vmc/reverse-proxy/api/orgs/{orgid}/sddcs/{sddcid}/sks-nsxt-manager/policy/api/v1/infra/services  are also failing in a 1.22v4 SDDC, but work fine in a 1.22v3 SDDC.

### Reproduction steps

1. Deploy an M1.22v4 SDDC
2. Build NATs with Terraform
3. The NAT rules do not forward traffic, even though you can see them in the UI
4. Manually create a new NAT rule in the UI
5. As soon as the new NAT manually-created rule gets saved, all of the Terraform-created NAT rules work
.

### Expected behavior

NAT rules published via Terraform should pass traffic immediately.

### Additional context

resource "nsxt_policy_nat_rule" "sddc_a_student_gateway_nat" {
  provider = nsxt.sddc_a_nsxt
  count    = local.student_count

  enabled      = true
  gateway_path = data.nsxt_policy_tier1_gateway.sddc_a_tier1_router.path
  display_name = "student${format("%03d", count.index + 1 + local.sddc_a_count_offset)}-nat"

  description = format(
    data.terraform_remote_state.phase1.outputs.name_specs.name_spec,
    "DNAT rule for VM: student${format("%03d", count.index + 1 + local.sddc_a_count_offset)}-gateway.",
  )

  action               = "DNAT"
  source_networks      = ["0.0.0.0/0"]
  destination_networks = [vmc_public_ip.sddc_a_public_ips[count.index].ip]
  translated_networks  = [vsphere_virtual_machine.sddc_a_student_backup_gateway_vms[count.index].default_ip_address]
  translated_ports     = 80
  service              = "/infra/services/HTTP"
  logging              = false
  firewall_match       = "MATCH_INTERNAL_ADDRESS"
  
}

**Comment by tvigneron** [comment]
Hello Patrick,

Is this done on the CGW or a new Tier-1?

Thomas

**Comment by kremerpatrick** [comment]
Hi - CGW

**Comment by kremerpatrick** [comment]
Ron Fuller had me generate a Terraform debug log if you would find that helpful, I don't necessarily want to post it here but I can forward it in email.

**Comment by tvigneron** [comment]
Hi Patrik,
Talked to Ron and he shared those, we will  get a look and reach out if required.Thanks for the info.

**Comment by annakhm** [comment]
Hi @kremerpatrick, it would be helpful if you could answer this: once the rules started working, does adding a new rule via terraform work as expected, or UI clicks are needed again?

**Comment by annakhm** [comment]
I'll close this since this seems to be NSX problem that no longer shows with 1.22v5. Please reopen if seen again. Thanks @kremerpatrick !
