### ISSUE TITLE
data source "nsxt_policy_service" doesn't find certain services since version 3.3.2

### ISSUE THREAD

**Issue by benzander** [vmware/terraform-provider-nsxt#991]
### Describe the bug

Since NSX TF Provider 3.3.2 there seems to be a bug in the nsxt_policy_service data source.
Certina predefined services cannot be found.
I saw that issue with:
IKE (Key Exchange)
IKE (NAT Traversal)

### Reproduction steps

```
data "nsxt_policy_service" "service" {
  display_name = "IKE (Key Exchange)"
}


data "nsxt_policy_service" "service2" {
  display_name = "IKE (NAT Traversal)"
}
```

Result is:
![image](https://github.com/vmware/terraform-provider-nsxt/assets/99820917/aea7ed49-81bc-47ea-b854-f70bff6c73be)

Version 3.3.1 works as expected

### Expected behavior

.

**Comment by annakhm** [comment]
Thanks for reporting this! This is related to changes introduced for the sake of multitenancy support, and is only relevant for display names containing special characters. Please expect the fix with next provider release in a couple of weeks.
