### ISSUE TITLE
Provider install: signature: openpgp: key expired

### ISSUE THREAD

**Issue by adeturner** [vmware/terraform-provider-nsxt#995]
### Describe the bug

│ Error: Failed to install provider
│
│ Error while installing vmware/nsxt v3.3.2: error checking signature:
│ openpgp: key expired

According to [https://github.com/hashicorp/terraform/issues/33984#issuecomment-1748712133](https://github.com/hashicorp/terraform/issues/33984#issuecomment-1748712133) you may need to update your pgp keys

EDIT: workaround: use terraform 1.5.7

### Reproduction steps

```
  required_providers {
    nsxt = {
      source  = "vmware/nsxt"
      version = ">=3.3.1"
    }
  }
```

terraform init

### Expected behavior

provider installs 

### Additional context

[https://github.com/hashicorp/terraform/issues/34000](https://github.com/hashicorp/terraform/issues/34000)
[https://github.com/confluentinc/terraform-provider-confluent/issues/315](https://github.com/confluentinc/terraform-provider-confluent/issues/315)
[https://github.com/hashicorp/terraform/issues/33984](https://github.com/hashicorp/terraform/issues/33984)

**Comment by hi9105** [comment]
Error: Failed to install provider
│ 
│ Error while installing cyrilgdn/postgresql v1.21.0: error checking
│ signature: openpgp: key expired

**Comment by adeturner** [comment]
> Error while installing cyrilgdn/postgresql v1.21.0: error checking

Hey @hi9105 - thats not to do with vmware provider... suggest you add that in the github for the provider and reference the main thread [https://github.com/hashicorp/terraform/issues/33984](https://github.com/hashicorp/terraform/issues/33984)

**Comment by salv-orlando** [comment]
Closing this issue as the problem did not lie with this specific provider.
