### ISSUE TITLE
Unable to create/ update security policies 

### ISSUE THREAD

**Issue by Girdhar1982** [vmware/terraform-provider-nsxt#996]
Using Version 3.3.2 is causing this error however 3.3.1 is fine: 
### Describe the bug

1. We are getting following error message when trying to create or update security policies. We didn't have any rule with sequence_number property

_│ Error: when sequence_number is specified in a rule, it must be consistent with rule order. To avoid confusion, it is recommended to either specify sequence numbers in all rules, or none                                                                                                                                    
│   with nsxt_policy_security_policy.application-database-fsw,_  

2. We have tried to update all the rules with sequence numbers however issue persists. we parsed the terraform state file to display all the rules and sequence_number in the policy and got following output

PS C:\myfiles> $state=Get-Content .\terraformstate.json | ConvertFrom-Json
PS C:\myfiles> $resources=$state.resources
PS C:\myfiles> $filterPol=$resources | ? { $_.type -eq "nsxt_policy_security_policy"}
foreach ($pol in $filterPol){
foreach ( $instance in $pol.instances)
{ 
foreach ($att in $instance.attributes ){
 if($att.display_name -ne "application-database-fsw"){continue;}
 Write-Host ("Policy Name :  " + $att.display_name + " Catagory " + $att.category + " Domain " + $att.domain) -ForegroundColor yellow
 foreach ($rule in  $att.rule) {
Write-Host "rule_id - "  -NoNewline ;Write-Host $rule.rule_id  -NoNewline; Write-Host " ==> sequence_number - "  -NoNewline ;Write-Host $rule.sequence_number -ForegroundColor yellow
 } } } }

Policy Name :  Application-database-fsw Catagory Application Domain cgw

rule_id - 9715 ==> sequence_number - 0
rule_id - 9829 ==> sequence_number - 1
rule_id - 9830 ==> sequence_number - 2
rule_id - 9714 ==> sequence_number - 3
rule_id - 9715 ==> sequence_number - 4
rule_id - 9716 ==> sequence_number - 5
rule_id - 9717 ==> sequence_number - 6
rule_id - 9718 ==> sequence_number - 7
rule_id - 9719 ==> sequence_number - 8
rule_id - 9720 ==> sequence_number - 9
rule_id - 9721 ==> sequence_number - 10
rule_id - 9722 ==> sequence_number - 11
rule_id - 9728 ==> sequence_number - 12
rule_id - 9729 ==> sequence_number - 13
rule_id - 9730 ==> sequence_number - 14
rule_id - 9731 ==> sequence_number - 15
rule_id - 9994 ==> sequence_number - 16
rule_id - 10004 ==> sequence_number - 18
rule_id - 10005 ==> sequence_number - 19
rule_id - 0 ==> sequence_number - 20 

### Reproduction steps

Unknown

### Expected behavior

terraform to automatically increment rules based on order they are defined in security policy. sequence_number is not mentioned in the rule.

**Comment by annakhm** [comment]
Hello, thank you for filing this issue. Could you please provide terraform config of the resource that is causing the issue?

**Comment by Girdhar1982** [comment]
Hi Anna, thanks for the response... this issue is resolved

**Comment by LukeTimeWalker** [comment]
![82yx7q](https://github.com/vmware/terraform-provider-nsxt/assets/45610865/eb6e2e8c-b43f-4e86-afd2-8587b171c08c)
